In [1]:
import pandas as pd

In [3]:
aisles = pd.read_csv('aisles.csv')
departments = pd.read_csv('departments.csv')
order_products_prior = pd.read_csv('order_products__prior.csv')
order_products_train = pd.read_csv('order_products__train.csv')
orders = pd.read_csv('orders.csv')
products = pd.read_csv('products.csv')

In [4]:
dfs = {
    'aisles': aisles,
    'departments': departments,
    'order_products_prior': order_products_prior,
    'order_products_train': order_products_train,
    'orders': orders,
    'products': products
}
for name, df in dfs.items():
    print(f'\n {name}: {df.shape}')
    print(df.head(5))
    print(f"\ncolumns: {df.columns.tolist()}")
    print(f"===============================================================================================================================================================================")

 aisles: (134, 2)
   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

columns: ['aisle_id', 'aisle']
===============================================================================================================================================================================

 departments: (21, 2)
   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

columns: ['department_id', 'department']
===============================================================================================================================================================================

 order_products_prior: (32434489, 4)
   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

columns: ['order_id', 'product_id', 'add_to_cart_order', 'reordered']
===============================================================================================================================================================================

 order_products_train: (1384617, 4)
   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

columns: ['order_id', 'product_id', 'add_to_cart_order', 'reordered']
===============================================================================================================================================================================

 orders: (3421083, 7)
   order_id  user_id eval_set  order_number  order_dow  order_hour_of_day  \
0   2539329        1    prior             1          2                  8
1   2398795        1    prior             2          3                  7
2    473747        1    prior             3          3                 12
3   2254736        1    prior             4          4                  7
4    431534        1    prior             5          4                 15

   days_since_prior_order
0                     NaN
1                    15.0
2                    21.0
3                    29.0
4                    28.0

columns: ['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow', 'order_hour_of_day', 'days_since_prior_order']
===============================================================================================================================================================================

 products: (49688, 4)
   product_id                                       product_name  aisle_id  \
0           1                         Chocolate Sandwich Cookies        61
1           2                                   All-Seasons Salt       104
2           3               Robust Golden Unsweetened Oolong Tea        94
3           4  Smart Ones Classic Favorites Mini Rigatoni Wit...        38
4           5                          Green Chile Anytime Sauce         5

   department_id
0             19
1             13
2              7
3              1
4             13

columns: ['product_id', 'product_name', 'aisle_id', 'department_id']
===============================================================================================================================================================================

In [5]:
orders.eval_set.value_counts()

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [6]:
order_products_prior.reordered.value_counts()

reordered
1    19126536
0    13307953
Name: count, dtype: int64

In [7]:
order_products_train.reordered.value_counts()

reordered
1    828824
0    555793
Name: count, dtype: int64

In [9]:
order_products_prior[(~order_products_prior.order_id .isin( order_products_train.order_id)) &
                       (~order_products_prior.product_id.isin(order_products_train.product_id))].order_id.nunique()

150868

In [10]:
prior_pairs = set(zip(order_products_prior.order_id, order_products_prior.product_id))
train_pairs = set(zip(order_products_train.order_id, order_products_train.product_id))

len(prior_pairs.intersection(train_pairs))

0

In [11]:
missing_prior = set(order_products_prior.order_id) - set(orders.order_id)
len(missing_prior)

0

In [12]:
missing_train = set(order_products_train.order_id) - set(orders.order_id)
len(missing_train)

0

In [13]:
test = orders[orders.eval_set == 'test']

In [14]:
test.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
38,2774568,3,test,13,5,15,11.0
44,329954,4,test,6,3,12,30.0
53,1528013,6,test,4,3,16,22.0
96,1376945,11,test,8,6,11,8.0
102,1356845,12,test,6,1,20,30.0

In [15]:
train = orders[orders.eval_set == 'train'].merge(order_products_train, on='order_id', how='left')

In [17]:
train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered
0,1187899,1,train,11,4,8,14.0,196,1,1
1,1187899,1,train,11,4,8,14.0,25133,2,1
2,1187899,1,train,11,4,8,14.0,38928,3,1
3,1187899,1,train,11,4,8,14.0,26405,4,1
4,1187899,1,train,11,4,8,14.0,39657,5,1

In [29]:
len(set(train.order_number)-set(test.order_number))

0