## Library imports

In [16]:
# libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import os
from pathlib import Path
from tkinter import Tk
from tkinter.filedialog import askdirectory

# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score

# Models
import lightgbm as lgb
from catboost import CatBoostClassifier
from xgboost import XGBClassifier

# Hyperparameter tuning
from sklearn.model_selection import StratifiedKFold
import optuna

# exporting the model
import joblib

## Load the dataset

In [17]:
cleaned_data_path = Path("../streamlit/cleaned_data")
if not cleaned_data_path.exists():
    root = Tk()
    root.withdraw()
    cleaned_data_path = Path(askdirectory(title="Select the directory containing the cleaned data"))

In [18]:
train=pd.read_parquet(cleaned_data_path/'train_final.parquet')
test=pd.read_parquet(cleaned_data_path/'test_final.parquet')

In [19]:
for col in train.columns:
    print(col)

SK_ID_CURR
TARGET
NAME_CONTRACT_TYPE
CODE_GENDER
FLAG_OWN_CAR
FLAG_OWN_REALTY
CNT_CHILDREN
AMT_INCOME_TOTAL
AMT_CREDIT
AMT_ANNUITY
AMT_GOODS_PRICE
NAME_TYPE_SUITE
NAME_INCOME_TYPE
NAME_EDUCATION_TYPE
NAME_FAMILY_STATUS
NAME_HOUSING_TYPE
REGION_POPULATION_RELATIVE
DAYS_BIRTH
DAYS_EMPLOYED
DAYS_REGISTRATION
DAYS_ID_PUBLISH
FLAG_EMP_PHONE
FLAG_WORK_PHONE
FLAG_CONT_MOBILE
FLAG_PHONE
FLAG_EMAIL
OCCUPATION_TYPE
CNT_FAM_MEMBERS
REGION_RATING_CLIENT
REGION_RATING_CLIENT_W_CITY
WEEKDAY_APPR_PROCESS_START
HOUR_APPR_PROCESS_START
REG_REGION_NOT_LIVE_REGION
REG_REGION_NOT_WORK_REGION
LIVE_REGION_NOT_WORK_REGION
REG_CITY_NOT_LIVE_CITY
REG_CITY_NOT_WORK_CITY
LIVE_CITY_NOT_WORK_CITY
ORGANIZATION_TYPE
OBS_30_CNT_SOCIAL_CIRCLE
DEF_30_CNT_SOCIAL_CIRCLE
OBS_60_CNT_SOCIAL_CIRCLE
DEF_60_CNT_SOCIAL_CIRCLE
DAYS_LAST_PHONE_CHANGE
AMT_REQ_CREDIT_BUREAU_HOUR
AMT_REQ_CREDIT_BUREAU_DAY
AMT_REQ_CREDIT_BUREAU_WEEK
AMT_REQ_CREDIT_BUREAU_MON
AMT_REQ_CREDIT_BUREAU_QRT
AMT_REQ_CREDIT_BUREAU_YEAR
EXT_SOURCE_MEAN
HAS_BUILDING_INFO
IS_HIGH_RISK_BUILDING
WALL_RISK
IS_LOW_RISK_HOUSETYPE
TOTAL_DOCUMENTS
LOAN_TO_INCOME
MAX_BUREAU_STATUS
AVG_BUREAU_STATUS
TOTAL_BUREAU_LOANS
ACTIVE_CREDIT_COUNT
CLOSED_CREDIT_COUNT
TOTAL_DEBT
AVG_DEBT
MAX_DEBT
TOTAL_CREDIT_SUM
AVG_CREDIT_SUM
MAX_CREDIT_SUM
TOTAL_OVERDUE
MAX_OVERDUE
HAS_OVERDUE
AVG_CREDIT_DAY_OVERDUE
MAX_CREDIT_DAY_OVERDUE
AVG_DAYS_CREDIT
MIN_DAYS_CREDIT
MAX_DAYS_CREDIT
AVG_DAYS_CREDIT_ENDDATE
AVG_DAYS_CREDIT_UPDATE
HAS_DPD_HISTORY
AVG_DPD_RATIO
AVG_SEVERE_DPD_RATIO
AVG_CLOSED_RATIO
AVG_MONTHS_HISTORY
ACTIVE_DEBT_RATIO
OVERDUE_TO_CREDIT_RATIO
CLOSED_TO_TOTAL_RATIO
OVERDUE_PER_ACTIVE_LOAN
DEBT_PER_ACTIVE_LOAN
TOTAL_PREV_APPLICATIONS
APPROVED_COUNT
REFUSED_COUNT
CANCELLED_COUNT
AVG_PREV_CREDIT
MAX_PREV_CREDIT
AVG_PREV_APPLICATION
AVG_GOODS_PRICE
AVG_PREV_ANNUITY
MAX_PREV_ANNUITY
AVG_CNT_PAYMENT
MAX_CNT_PAYMENT
AVG_DAYS_DECISION
MIN_DAYS_DECISION
MAX_DAYS_DECISION
AVG_DAYS_LAST_DUE_MISSING
AVG_INSURED_MISSING
TOTAL_INSTALLMENTS
AVG_PAYMENT_DELAY
STD_PAYMENT_DELAY
MAX_PAYMENT_DELAY
AVG_PAYMENT_RATIO
MIN_PAYMENT_RATIO
INSTALLMENT_LATE_PAYMENT_RATIO
PAYMENT_RATIO_STD
UNDER_PAYMENT_RATIO
AVG_AMT_PAYMENT
MAX_AMT_PAYMENT
AVG_AMT_INSTALMENT
MAX_AMT_INSTALMENT
AVG_DAYS_INSTALMENT
AVG_DAYS_ENTRY_PAYMENT
DPD_OVER_30_MEAN
DPD_OVER_30_MAX
DPD_OVER_30_STD
DPD_OVER_60_MEAN
DPD_OVER_60_MAX
DPD_OVER_60_STD
DPD_OVER_90_MEAN
DPD_OVER_90_MAX
DPD_OVER_90_STD
TOTAL_CC_LOANS
AVG_CC_BALANCE
MAX_CC_BALANCE
AVG_CC_LIMIT
MAX_CC_LIMIT
AVG_LIMIT_USAGE_RATIO
MAX_LIMIT_USAGE_RATIO
MIN_CC_PAYMENT_RATIO
AVG_CC_DPD
MAX_CC_DPD
CC_LATE_PAYMENT_RATIO
AVG_DRAWINGS_CURRENT
MAX_DRAWINGS_CURRENT
AVG_PAYMENT_CURRENT
AVG_RECEIVABLE
CC_AVG_MONTHS_BALANCE
TOTAL_POS_LOANS
POS_AVG_MONTHS_BALANCE
MIN_MONTHS_BALANCE
MAX_MONTHS_BALANCE
AVG_CNT_INSTALMENT
MAX_CNT_INSTALMENT
AVG_CNT_INSTALMENT_FUTURE
MAX_CNT_INSTALMENT_FUTURE
AVG_POS_DPD
MAX_POS_DPD
AVG_POS_DPD_DEF
MAX_POS_DPD_DEF
LATE_PAYMENT_RATIO
LATE_PAYMENT_DEF_RATIO

### target separation

In [20]:
X = train.drop(columns=['SK_ID_CURR', 'TARGET'])
y = train['TARGET']

### endoding categorical features

In [21]:
cat_cols = X.select_dtypes(include='object').columns

len(cat_cols)

0

In [22]:
cat_cols

Index([], dtype='object')

In [23]:
encoders = {}
for col in cat_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])
    encoders[col] = le

### split the data into training and validation sets

In [24]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2,stratify= y ,random_state=42)

# model testing

### base model testing

In [25]:
model = lgb.LGBMClassifier(
    n_estimators      = 1000,
    learning_rate     = 0.05,
    num_leaves        = 63,
    max_depth         = -1,
    min_child_samples = 50,
    subsample         = 0.8,
    colsample_bytree  = 0.8,
    reg_alpha         = 0.1,
    reg_lambda        = 0.1,
    class_weight      = "balanced",   # handles class imbalance
    random_state      = 42,
    n_jobs            = -1,
    verbose           = -1,
)

model.fit(
    X_train, y_train,
    eval_set              = [(X_val, y_val)],
    callbacks             = [lgb.early_stopping(50, verbose=False),
                                lgb.log_evaluation(period=-1)],
)

pred_prob = model.predict_proba(X_val)[:, 1]
auc       = roc_auc_score(y_val, pred_prob)

In [26]:
auc

np.float64(0.7664056260372388)

In [27]:
pred = model.predict(X_val)

confusion_matrix(y_val, pred)

array([[48340,  8165],
       [ 2525,  2437]])

In [28]:
print(classification_report(y_val,pred))

              precision    recall  f1-score   support

           0       0.95      0.86      0.90     56505
           1       0.23      0.49      0.31      4962

    accuracy                           0.83     61467
   macro avg       0.59      0.67      0.61     61467
weighted avg       0.89      0.83      0.85     61467

In [29]:
feature_imp = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': model.feature_importances_
}).sort_values(
    by='Importance',
    ascending=False
)

feature_imp.tail(50)

                         Feature  Importance
38      DEF_30_CNT_SOCIAL_CIRCLE          92
13             NAME_HOUSING_TYPE          85
141               AVG_RECEIVABLE          83
135                   AVG_CC_DPD          83
4                   CNT_CHILDREN          81
22                    FLAG_PHONE          81
40      DEF_60_CNT_SOCIAL_CIRCLE          78
9                NAME_TYPE_SUITE          75
45     AMT_REQ_CREDIT_BUREAU_MON          75
20               FLAG_WORK_PHONE          66
137        CC_LATE_PAYMENT_RATIO          64
0             NAME_CONTRACT_TYPE          63
10              NAME_INCOME_TYPE          63
33        REG_CITY_NOT_LIVE_CITY          59
26          REGION_RATING_CLIENT          54
118             DPD_OVER_30_MEAN          47
34        REG_CITY_NOT_WORK_CITY          46
3                FLAG_OWN_REALTY          46
120              DPD_OVER_30_STD          46
49             HAS_BUILDING_INFO          37
52         IS_LOW_RISK_HOUSETYPE          34
84       OVERDUE_PER_ACTIVE_LOAN          32
55             MAX_BUREAU_STATUS          29
70        MAX_CREDIT_DAY_OVERDUE          28
44    AMT_REQ_CREDIT_BUREAU_WEEK          27
66                 TOTAL_OVERDUE          26
35       LIVE_CITY_NOT_WORK_CITY          26
78          AVG_SEVERE_DPD_RATIO          25
50         IS_HIGH_RISK_BUILDING          22
123              DPD_OVER_60_STD          20
67                   MAX_OVERDUE          20
136                   MAX_CC_DPD          18
23                    FLAG_EMAIL          17
76               HAS_DPD_HISTORY          15
121             DPD_OVER_60_MEAN          14
124             DPD_OVER_90_MEAN          12
32   LIVE_REGION_NOT_WORK_REGION          12
69        AVG_CREDIT_DAY_OVERDUE           9
82       OVERDUE_TO_CREDIT_RATIO           8
43     AMT_REQ_CREDIT_BUREAU_DAY           8
31    REG_REGION_NOT_WORK_REGION           8
21              FLAG_CONT_MOBILE           7
126              DPD_OVER_90_STD           7
19                FLAG_EMP_PHONE           5
30    REG_REGION_NOT_LIVE_REGION           5
68                   HAS_OVERDUE           1
42    AMT_REQ_CREDIT_BUREAU_HOUR           0
119              DPD_OVER_30_MAX           0
122              DPD_OVER_60_MAX           0
125              DPD_OVER_90_MAX           0

In [30]:
cv = StratifiedKFold(n_splits=5,shuffle=True,random_state=42)

In [31]:
cv_scores = cross_val_score(model,X,y,scoring='roc_auc',cv=cv,n_jobs=-1)

In [32]:
print(cv_scores)
print(cv_scores.mean())
print(cv_scores.std())

[0.77346374 0.77522504 0.7596798  0.76727879 0.77199067]
0.76952760704354
0.005586718041530355

## hyperparameter tuning with optuna for lightgbm

In [79]:
def objective(trial):
    params={
        'objective': 'binary',
        'metric': 'auc',
        'boosting_type': 'gbdt',
        'class_weight': 'balanced',
        'n_estimators': trial.suggest_int('n_estimators', 300,2000),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 20, 150),
        'max_depth': trial.suggest_int('max_depth', 3, 15),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-3, 10.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-3, 10.0, log=True),
        'random_state': 42,
        'n_jobs': -1,
        'verbose': -1,
    }
    model = lgb.LGBMClassifier(**params)
    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        callbacks=[lgb.early_stopping(50, verbose=False)],
    )
    pred_prob = model.predict_proba(X_val)[:, 1]
    auc = roc_auc_score(y_val, pred_prob)
    return auc

In [ ]:
lgb_study = optuna.create_study(direction='maximize')
lgb_study.optimize(objective, n_trials=50)

[I 2026-05-28 22:06:44,846] A new study created in memory with name: no-name-b9ef83a7-f892-4769-b847-9b8b5842febe
[I 2026-05-28 22:07:15,701] Trial 0 finished with value: 0.7750925973778023 and parameters: {'n_estimators': 1410, 'learning_rate': 0.013291023941685578, 'num_leaves': 88, 'max_depth': 4, 'subsample': 0.7021300592404628, 'colsample_bytree': 0.967149974778681, 'reg_alpha': 0.07634724593613502, 'reg_lambda': 0.17949808061534578}. Best is trial 0 with value: 0.7750925973778023.
[I 2026-05-28 22:07:30,636] Trial 1 finished with value: 0.776491277965257 and parameters: {'n_estimators': 748, 'learning_rate': 0.03543860682357844, 'num_leaves': 27, 'max_depth': 4, 'subsample': 0.6389011108898541, 'colsample_bytree': 0.7231821108536258, 'reg_alpha': 0.0012648186229355647, 'reg_lambda': 0.002629973614091467}. Best is trial 1 with value: 0.776491277965257.
[I 2026-05-28 22:08:00,372] Trial 2 finished with value: 0.7784138480859094 and parameters: {'n_estimators': 1255, 'learning_rate': 0.01503088362335839, 'num_leaves': 43, 'max_depth': 10, 'subsample': 0.8730646136847167, 'colsample_bytree': 0.7134227129090293, 'reg_alpha': 3.434735201514473, 'reg_lambda': 0.020928225522786226}. Best is trial 2 with value: 0.7784138480859094.
[I 2026-05-28 22:08:13,880] Trial 3 finished with value: 0.7782939598536702 and parameters: {'n_estimators': 589, 'learning_rate': 0.04843374949874149, 'num_leaves': 44, 'max_depth': 8, 'subsample': 0.7102485861988372, 'colsample_bytree': 0.7102721710089344, 'reg_alpha': 3.6841535652134416, 'reg_lambda': 0.0015672019841926853}. Best is trial 2 with value: 0.7784138480859094.
[I 2026-05-28 22:08:27,586] Trial 4 finished with value: 0.7761522104762855 and parameters: {'n_estimators': 1651, 'learning_rate': 0.04857027767510618, 'num_leaves': 65, 'max_depth': 6, 'subsample': 0.9198637364179134, 'colsample_bytree': 0.839841344713131, 'reg_alpha': 0.3968872804487413, 'reg_lambda': 0.009939592112202137}. Best is trial 2 with value: 0.7784138480859094.
[I 2026-05-28 22:08:47,639] Trial 5 finished with value: 0.7741666253830858 and parameters: {'n_estimators': 316, 'learning_rate': 0.019790076912596266, 'num_leaves': 112, 'max_depth': 11, 'subsample': 0.7060714553830651, 'colsample_bytree': 0.863607102567814, 'reg_alpha': 0.1768704891962826, 'reg_lambda': 0.0021165614368168014}. Best is trial 2 with value: 0.7784138480859094.
[I 2026-05-28 22:09:06,441] Trial 6 finished with value: 0.7764864808666563 and parameters: {'n_estimators': 1617, 'learning_rate': 0.03741905301642832, 'num_leaves': 86, 'max_depth': 5, 'subsample': 0.872276177527959, 'colsample_bytree': 0.9947113581542386, 'reg_alpha': 0.010638463158484206, 'reg_lambda': 0.052567822691149034}. Best is trial 2 with value: 0.7784138480859094.
[I 2026-05-28 22:09:26,058] Trial 7 finished with value: 0.7757543080887892 and parameters: {'n_estimators': 1079, 'learning_rate': 0.026238923113588664, 'num_leaves': 78, 'max_depth': 3, 'subsample': 0.7548663643205475, 'colsample_bytree': 0.9907796655124396, 'reg_alpha': 0.0017776025262309769, 'reg_lambda': 0.0032812217978140288}. Best is trial 2 with value: 0.7784138480859094.
[I 2026-05-28 22:09:38,869] Trial 8 finished with value: 0.7777010634329442 and parameters: {'n_estimators': 1675, 'learning_rate': 0.06963570607961808, 'num_leaves': 81, 'max_depth': 5, 'subsample': 0.7894899912863694, 'colsample_bytree': 0.7151214726534304, 'reg_alpha': 2.945535911910973, 'reg_lambda': 0.04720623062556443}. Best is trial 2 with value: 0.7784138480859094.
[I 2026-05-28 22:09:48,984] Trial 9 finished with value: 0.7741799716603821 and parameters: {'n_estimators': 1069, 'learning_rate': 0.09018933967429275, 'num_leaves': 113, 'max_depth': 11, 'subsample': 0.8856525379777276, 'colsample_bytree': 0.8832479277539289, 'reg_alpha': 0.026543825805450363, 'reg_lambda': 0.029324156234403286}. Best is trial 2 with value: 0.7784138480859094.
[I 2026-05-28 22:10:32,759] Trial 10 finished with value: 0.7786472724071851 and parameters: {'n_estimators': 1954, 'learning_rate': 0.010913580714536946, 'num_leaves': 20, 'max_depth': 15, 'subsample': 0.9981905374055073, 'colsample_bytree': 0.6000188653740858, 'reg_alpha': 9.864029479314254, 'reg_lambda': 3.7920307846792376}. Best is trial 10 with value: 0.7786472724071851.
[I 2026-05-28 22:11:19,544] Trial 11 finished with value: 0.7791674027270561 and parameters: {'n_estimators': 1932, 'learning_rate': 0.010102458395317352, 'num_leaves': 26, 'max_depth': 15, 'subsample': 0.9744126533470757, 'colsample_bytree': 0.6100880279062015, 'reg_alpha': 7.613787769274988, 'reg_lambda': 5.681590044622019}. Best is trial 11 with value: 0.7791674027270561.
[I 2026-05-28 22:12:15,497] Trial 12 finished with value: 0.7798351053530235 and parameters: {'n_estimators': 1994, 'learning_rate': 0.010401072545354509, 'num_leaves': 32, 'max_depth': 15, 'subsample': 0.9954795767943546, 'colsample_bytree': 0.6023681058048996, 'reg_alpha': 9.318750956533046, 'reg_lambda': 8.453194271004552}. Best is trial 12 with value: 0.7798351053530235.
[I 2026-05-28 22:12:58,771] Trial 13 finished with value: 0.7791997020020949 and parameters: {'n_estimators': 2000, 'learning_rate': 0.017196034483710793, 'num_leaves': 143, 'max_depth': 15, 'subsample': 0.9997120268968551, 'colsample_bytree': 0.600954395758053, 'reg_alpha': 1.410304932740045, 'reg_lambda': 9.478690523255617}. Best is trial 12 with value: 0.7798351053530235.
[I 2026-05-28 22:13:27,282] Trial 14 finished with value: 0.777240763097479 and parameters: {'n_estimators': 1985, 'learning_rate': 0.019215531677942238, 'num_leaves': 145, 'max_depth': 13, 'subsample': 0.9351080542449842, 'colsample_bytree': 0.6532883473775789, 'reg_alpha': 0.7947217087309816, 'reg_lambda': 1.021783739097182}. Best is trial 12 with value: 0.7798351053530235.
[I 2026-05-28 22:14:02,185] Trial 15 finished with value: 0.777216189112826 and parameters: {'n_estimators': 1779, 'learning_rate': 0.019417507956985564, 'num_leaves': 149, 'max_depth': 13, 'subsample': 0.9551920994859573, 'colsample_bytree': 0.6556715416842874, 'reg_alpha': 1.0969304573495406, 'reg_lambda': 0.993878538241071}. Best is trial 12 with value: 0.7798351053530235.
[I 2026-05-28 22:14:53,047] Trial 16 finished with value: 0.7781231011113182 and parameters: {'n_estimators': 1461, 'learning_rate': 0.014616793539547994, 'num_leaves': 113, 'max_depth': 13, 'subsample': 0.825789997658923, 'colsample_bytree': 0.7702176264309063, 'reg_alpha': 1.2422416662602094, 'reg_lambda': 9.016245094074094}. Best is trial 12 with value: 0.7798351053530235.
[I 2026-05-28 22:15:17,610] Trial 17 finished with value: 0.776922474713673 and parameters: {'n_estimators': 1793, 'learning_rate': 0.024931055628524695, 'num_leaves': 128, 'max_depth': 15, 'subsample': 0.9914421631132859, 'colsample_bytree': 0.6544422146697887, 'reg_alpha': 0.2858702967912572, 'reg_lambda': 1.2920945464231741}. Best is trial 12 with value: 0.7798351053530235.
[I 2026-05-28 22:15:50,362] Trial 18 finished with value: 0.7773103335103446 and parameters: {'n_estimators': 877, 'learning_rate': 0.01262498763659371, 'num_leaves': 57, 'max_depth': 8, 'subsample': 0.9143975889261686, 'colsample_bytree': 0.7764394601681873, 'reg_alpha': 1.6290635268722053, 'reg_lambda': 0.24705650559295092}. Best is trial 12 with value: 0.7798351053530235.
[I 2026-05-28 22:16:19,485] Trial 19 finished with value: 0.7780924282132028 and parameters: {'n_estimators': 1447, 'learning_rate': 0.016888559323495984, 'num_leaves': 99, 'max_depth': 12, 'subsample': 0.8320949992033212, 'colsample_bytree': 0.6368933562486838, 'reg_alpha': 0.04954480267163281, 'reg_lambda': 2.342302580304922}. Best is trial 12 with value: 0.7798351053530235.
[I 2026-05-28 22:16:47,175] Trial 20 finished with value: 0.7789928632369302 and parameters: {'n_estimators': 1263, 'learning_rate': 0.02483417703343086, 'num_leaves': 130, 'max_depth': 14, 'subsample': 0.6065467737902112, 'colsample_bytree': 0.683615281553902, 'reg_alpha': 0.44905123820348347, 'reg_lambda': 9.572200213335854}. Best is trial 12 with value: 0.7798351053530235.
[I 2026-05-28 22:17:36,048] Trial 21 finished with value: 0.7800329633789492 and parameters: {'n_estimators': 1998, 'learning_rate': 0.011562008266452931, 'num_leaves': 35, 'max_depth': 15, 'subsample': 0.9674671459114446, 'colsample_bytree': 0.6018182304427421, 'reg_alpha': 8.957807476144229, 'reg_lambda': 3.9415992094086296}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:18:24,212] Trial 22 finished with value: 0.7788177174220743 and parameters: {'n_estimators': 1830, 'learning_rate': 0.011662946160646314, 'num_leaves': 39, 'max_depth': 14, 'subsample': 0.9614017078976105, 'colsample_bytree': 0.6005921809824591, 'reg_alpha': 5.757370199113606, 'reg_lambda': 0.45729802992082164}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:19:13,163] Trial 23 finished with value: 0.7791859990631926 and parameters: {'n_estimators': 1839, 'learning_rate': 0.010423979947832911, 'num_leaves': 57, 'max_depth': 14, 'subsample': 0.9996774528745015, 'colsample_bytree': 0.6311405555248556, 'reg_alpha': 2.278573219049625, 'reg_lambda': 2.7721302187562955}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:19:44,425] Trial 24 finished with value: 0.7791945946078971 and parameters: {'n_estimators': 2000, 'learning_rate': 0.016119750627243107, 'num_leaves': 36, 'max_depth': 12, 'subsample': 0.9428570189469363, 'colsample_bytree': 0.6854193091967455, 'reg_alpha': 7.553506727563617, 'reg_lambda': 4.856919036263001}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:20:30,986] Trial 25 finished with value: 0.7790951502189135 and parameters: {'n_estimators': 1608, 'learning_rate': 0.012390323255679434, 'num_leaves': 67, 'max_depth': 15, 'subsample': 0.9010948024854208, 'colsample_bytree': 0.6798710723253995, 'reg_alpha': 4.432298206795495, 'reg_lambda': 0.588654056138666}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:20:57,545] Trial 26 finished with value: 0.7785112880366674 and parameters: {'n_estimators': 1734, 'learning_rate': 0.017628480607335417, 'num_leaves': 51, 'max_depth': 12, 'subsample': 0.9595657579381461, 'colsample_bytree': 0.6319342654142329, 'reg_alpha': 0.64309117700075, 'reg_lambda': 2.148418636276551}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:21:25,689] Trial 27 finished with value: 0.7790262681629477 and parameters: {'n_estimators': 1557, 'learning_rate': 0.022078286678160173, 'num_leaves': 70, 'max_depth': 14, 'subsample': 0.8498149166035422, 'colsample_bytree': 0.8067590937538435, 'reg_alpha': 2.1138158833190794, 'reg_lambda': 7.884408277216072}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:22:18,281] Trial 28 finished with value: 0.7789053420454352 and parameters: {'n_estimators': 1885, 'learning_rate': 0.014035491209911977, 'num_leaves': 100, 'max_depth': 9, 'subsample': 0.9759540112934924, 'colsample_bytree': 0.7479064111663316, 'reg_alpha': 8.824922845171834, 'reg_lambda': 3.694732264418866}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:22:56,206] Trial 29 finished with value: 0.7768552761004873 and parameters: {'n_estimators': 1332, 'learning_rate': 0.013338701359552837, 'num_leaves': 32, 'max_depth': 13, 'subsample': 0.9383690031847405, 'colsample_bytree': 0.9357870260193679, 'reg_alpha': 0.15943276594480474, 'reg_lambda': 0.2789242604939107}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:23:42,165] Trial 30 finished with value: 0.7782964493516802 and parameters: {'n_estimators': 1516, 'learning_rate': 0.011981516460493686, 'num_leaves': 137, 'max_depth': 15, 'subsample': 0.7790213042259893, 'colsample_bytree': 0.6226263066173465, 'reg_alpha': 0.004586628850132776, 'reg_lambda': 1.6136638785854867}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:24:20,893] Trial 31 finished with value: 0.7796675528637591 and parameters: {'n_estimators': 1999, 'learning_rate': 0.016215096997219812, 'num_leaves': 36, 'max_depth': 12, 'subsample': 0.9407033669057996, 'colsample_bytree': 0.6826642492566934, 'reg_alpha': 5.724925869477958, 'reg_lambda': 4.611191957862579}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:25:07,803] Trial 32 finished with value: 0.7790503107218077 and parameters: {'n_estimators': 1998, 'learning_rate': 0.01002006894908252, 'num_leaves': 48, 'max_depth': 14, 'subsample': 0.977562393633074, 'colsample_bytree': 0.6748367865158416, 'reg_alpha': 5.076826499896281, 'reg_lambda': 5.165703053118312}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:25:40,435] Trial 33 finished with value: 0.7774643435584292 and parameters: {'n_estimators': 1867, 'learning_rate': 0.014576236479494579, 'num_leaves': 20, 'max_depth': 11, 'subsample': 0.9247349786045727, 'colsample_bytree': 0.6481472608352913, 'reg_alpha': 3.3956350176869856, 'reg_lambda': 0.11044621692811209}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:25:59,034] Trial 34 finished with value: 0.7782349822905029 and parameters: {'n_estimators': 1730, 'learning_rate': 0.031087497113863546, 'num_leaves': 30, 'max_depth': 10, 'subsample': 0.9024750966834092, 'colsample_bytree': 0.6230907725108665, 'reg_alpha': 2.04584979526408, 'reg_lambda': 0.5936643519422049}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:26:36,636] Trial 35 finished with value: 0.7794971399484146 and parameters: {'n_estimators': 1888, 'learning_rate': 0.01582499815877525, 'num_leaves': 41, 'max_depth': 13, 'subsample': 0.9595692667351967, 'colsample_bytree': 0.7051975598841833, 'reg_alpha': 4.448905618545508, 'reg_lambda': 6.253086940620354}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:27:15,987] Trial 36 finished with value: 0.7786522335701245 and parameters: {'n_estimators': 1876, 'learning_rate': 0.013365363370290548, 'num_leaves': 42, 'max_depth': 12, 'subsample': 0.6751761111910174, 'colsample_bytree': 0.7348282331600853, 'reg_alpha': 5.014705475857765, 'reg_lambda': 2.8615238327586545}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:27:32,742] Trial 37 finished with value: 0.7777688755040921 and parameters: {'n_estimators': 424, 'learning_rate': 0.021624421734332933, 'num_leaves': 55, 'max_depth': 10, 'subsample': 0.870739351393846, 'colsample_bytree': 0.710715093033828, 'reg_alpha': 9.980416940395155, 'reg_lambda': 1.6425670070588958}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:27:47,148] Trial 38 finished with value: 0.7787117639587811 and parameters: {'n_estimators': 828, 'learning_rate': 0.04494772264896612, 'num_leaves': 37, 'max_depth': 13, 'subsample': 0.9503535236620928, 'colsample_bytree': 0.6955856040105401, 'reg_alpha': 3.3970544256651625, 'reg_lambda': 5.443760465400304}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:28:21,415] Trial 39 finished with value: 0.7777746819550377 and parameters: {'n_estimators': 1702, 'learning_rate': 0.016048014665192966, 'num_leaves': 45, 'max_depth': 14, 'subsample': 0.7304689613794229, 'colsample_bytree': 0.7472011399127425, 'reg_alpha': 0.0779162986463423, 'reg_lambda': 0.8234278869536337}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:28:40,932] Trial 40 finished with value: 0.777336890533527 and parameters: {'n_estimators': 1905, 'learning_rate': 0.02837710176233664, 'num_leaves': 26, 'max_depth': 7, 'subsample': 0.8922093449388715, 'colsample_bytree': 0.8053743706169117, 'reg_alpha': 0.7672714657606845, 'reg_lambda': 0.008035722777083283}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:29:11,144] Trial 41 finished with value: 0.7794937159969971 and parameters: {'n_estimators': 2000, 'learning_rate': 0.01755061095912108, 'num_leaves': 32, 'max_depth': 15, 'subsample': 0.9762353093720266, 'colsample_bytree': 0.6187718884577654, 'reg_alpha': 5.706472711426916, 'reg_lambda': 6.673963122779838}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:29:54,865] Trial 42 finished with value: 0.7789097468162691 and parameters: {'n_estimators': 1785, 'learning_rate': 0.011611405607453584, 'num_leaves': 33, 'max_depth': 14, 'subsample': 0.9744916939040009, 'colsample_bytree': 0.6567440615079606, 'reg_alpha': 5.5844254343748965, 'reg_lambda': 3.4550546267180073}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:30:35,554] Trial 43 finished with value: 0.7789462974976514 and parameters: {'n_estimators': 1891, 'learning_rate': 0.015506139194203078, 'num_leaves': 26, 'max_depth': 15, 'subsample': 0.9750950031745403, 'colsample_bytree': 0.6663292437934202, 'reg_alpha': 2.6239914829495, 'reg_lambda': 5.93440762061744}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:31:27,425] Trial 44 finished with value: 0.7796691328746735 and parameters: {'n_estimators': 1621, 'learning_rate': 0.0113952363443093, 'num_leaves': 62, 'max_depth': 13, 'subsample': 0.9187930006758347, 'colsample_bytree': 0.614346031779204, 'reg_alpha': 6.88187222736672, 'reg_lambda': 2.0181349720376023}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:32:16,809] Trial 45 finished with value: 0.7786214108741345 and parameters: {'n_estimators': 1645, 'learning_rate': 0.01131336523449508, 'num_leaves': 50, 'max_depth': 11, 'subsample': 0.9183108352054831, 'colsample_bytree': 0.6446608890727924, 'reg_alpha': 3.5733011828561017, 'reg_lambda': 1.809752059802412}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:32:28,213] Trial 46 finished with value: 0.7780312500479264 and parameters: {'n_estimators': 1924, 'learning_rate': 0.06490196244998821, 'num_leaves': 63, 'max_depth': 13, 'subsample': 0.9310948253494694, 'colsample_bytree': 0.6947381846542542, 'reg_alpha': 7.077623617559232, 'reg_lambda': 4.170239944133343}. Best is trial 21 with value: 0.7800329633789492.
[I 2026-05-28 22:33:22,413] Trial 47 finished with value: 0.7803364396062585 and parameters: {'n_estimators': 1756, 'learning_rate': 0.01331366272815625, 'num_leaves': 74, 'max_depth': 12, 'subsample': 0.8567488572903952, 'colsample_bytree': 0.6144388426493165, 'reg_alpha': 9.928108621631159, 'reg_lambda': 3.2730873799027798}. Best is trial 47 with value: 0.7803364396062585.
[I 2026-05-28 22:34:27,644] Trial 48 finished with value: 0.7802271049909406 and parameters: {'n_estimators': 1566, 'learning_rate': 0.010859529347389789, 'num_leaves': 73, 'max_depth': 12, 'subsample': 0.8548575110165468, 'colsample_bytree': 0.6128999738204464, 'reg_alpha': 9.969239144273272, 'reg_lambda': 1.2720608094364194}. Best is trial 47 with value: 0.7803364396062585.
[I 2026-05-28 22:35:13,469] Trial 49 finished with value: 0.7780604642000735 and parameters: {'n_estimators': 1145, 'learning_rate': 0.010930541836311458, 'num_leaves': 80, 'max_depth': 9, 'subsample': 0.856170901856997, 'colsample_bytree': 0.6115856184395758, 'reg_alpha': 0.022396615079095777, 'reg_lambda': 1.2275245251611286}. Best is trial 47 with value: 0.7803364396062585.

In [ ]:
lgb_study.best_params

{'n_estimators': 1756,
 'learning_rate': 0.01331366272815625,
 'num_leaves': 74,
 'max_depth': 12,
 'subsample': 0.8567488572903952,
 'colsample_bytree': 0.6144388426493165,
 'reg_alpha': 9.928108621631159,
 'reg_lambda': 3.2730873799027798}

In [ ]:
lgb_study.best_value

0.7803364396062585

## tunned lightgbm model

In [ ]:
lgb_model = lgb.LGBMClassifier(
    **lgb_study.best_params,
    class_weight      = "balanced",
    random_state      = 42,
    n_jobs            = -1,
    verbose           = -1,
)

In [61]:
lgb_model.fit(
    X_train,
    y_train,
    eval_set=(X_val, y_val)
)

LGBMClassifier(class_weight='balanced', colsample_bytree=0.6144388426493165,
               learning_rate=0.01331366272815625, max_depth=12,
               min_child_samples=50, n_estimators=1756, n_jobs=-1,
               num_leaves=74, random_state=42, reg_alpha=9.928108621631159,
               reg_lambda=3.2730873799027798, subsample=0.8567488572903952,
               verbose=-1)

In [ ]:
lgb_pred = lgb_model.predict_proba(X_val)[:,1]
lgb_auc = roc_auc_score(y_val, lgb_pred)
print(lgb_auc)

0.780350392208285

### hyperparameter tuning with optuna for catboost

In [ ]:
# =========================================
# OPTUNA OBJECTIVE FUNCTION FOR CATBOOST
# =========================================

def objective(trial):

    params = {

        'loss_function': 'Logloss',

        'eval_metric': 'AUC',

        'iterations': trial.suggest_int(
            'iterations',
            300,
            2000
        ),

        'learning_rate': trial.suggest_float(
            'learning_rate',
            0.01,
            0.1,
            log=True
        ),

        'depth': trial.suggest_int(
            'depth',
            4,
            10
        ),

        'l2_leaf_reg': trial.suggest_float(
            'l2_leaf_reg',
            1e-3,
            10.0,
            log=True
        ),

        'subsample': trial.suggest_float(
            'subsample',
            0.6,
            1.0
        ),

        'random_strength': trial.suggest_float(
            'random_strength',
            1e-3,
            10.0,
            log=True
        ),

        'bagging_temperature': trial.suggest_float(
            'bagging_temperature',
            0,
            10
        ),

        'scale_pos_weight': trial.suggest_float(
            'scale_pos_weight',
            1,
            10
        ),

        'random_state': 42,

        'verbose': 0
    }

    # =====================================
    # MODEL
    # =====================================

    cat_model = CatBoostClassifier(
        **params
    )

    # =====================================
    # TRAIN
    # =====================================

    cat_model.fit(

        X_train,
        y_train,

        eval_set=(X_val, y_val),

        early_stopping_rounds=50,

        verbose=False
    )

    # =====================================
    # PREDICTION
    # =====================================

    pred_prob = cat_model.predict_proba(X_val)[:,1]

    # =====================================
    # ROC-AUC
    # =====================================

    auc = roc_auc_score(y_val,pred_prob)

    return auc

In [ ]:
cat_study = optuna.create_study(direction='maximize')

cat_study.optimize(objective,n_trials=75)

[I 2026-05-28 22:53:52,588] A new study created in memory with name: no-name-0676b5b0-4517-4861-aeb4-3a20f8f63e36
[I 2026-05-28 22:54:06,477] Trial 0 finished with value: 0.7714439669815525 and parameters: {'iterations': 1295, 'learning_rate': 0.05906329856521286, 'depth': 8, 'l2_leaf_reg': 0.12978727383872166, 'subsample': 0.7273884719359953, 'random_strength': 0.03289372924152347, 'bagging_temperature': 5.059569565681148, 'scale_pos_weight': 9.107935794226211}. Best is trial 0 with value: 0.7714439669815525.
[I 2026-05-28 22:54:24,291] Trial 1 finished with value: 0.7775268271051835 and parameters: {'iterations': 866, 'learning_rate': 0.056992785034403644, 'depth': 5, 'l2_leaf_reg': 0.3922040849042633, 'subsample': 0.6006743679474543, 'random_strength': 0.02993362187767755, 'bagging_temperature': 7.510896274521298, 'scale_pos_weight': 8.7770499693569}. Best is trial 1 with value: 0.7775268271051835.
[I 2026-05-28 22:55:12,934] Trial 2 finished with value: 0.7646618789126002 and parameters: {'iterations': 818, 'learning_rate': 0.013558475418458758, 'depth': 8, 'l2_leaf_reg': 0.1677307967354123, 'subsample': 0.9939213875968813, 'random_strength': 7.201889408916632, 'bagging_temperature': 7.206450123082001, 'scale_pos_weight': 4.275481307499079}. Best is trial 1 with value: 0.7775268271051835.
[I 2026-05-28 22:55:45,850] Trial 3 finished with value: 0.7754648771955241 and parameters: {'iterations': 652, 'learning_rate': 0.024933314751600197, 'depth': 6, 'l2_leaf_reg': 0.035984880062215854, 'subsample': 0.8527052488432882, 'random_strength': 0.7536398721353446, 'bagging_temperature': 2.592369660650764, 'scale_pos_weight': 4.56165348281484}. Best is trial 1 with value: 0.7775268271051835.
[I 2026-05-28 22:56:34,467] Trial 4 finished with value: 0.775983402538168 and parameters: {'iterations': 975, 'learning_rate': 0.013360497737592819, 'depth': 7, 'l2_leaf_reg': 1.6516640319116174, 'subsample': 0.6593214389151573, 'random_strength': 0.023783964499822563, 'bagging_temperature': 4.223165893151737, 'scale_pos_weight': 4.2244807837665554}. Best is trial 1 with value: 0.7775268271051835.
[I 2026-05-28 22:57:41,657] Trial 5 finished with value: 0.7735709719681455 and parameters: {'iterations': 1976, 'learning_rate': 0.01111747903016024, 'depth': 4, 'l2_leaf_reg': 0.06440327820079111, 'subsample': 0.7923642569675511, 'random_strength': 1.2199930571309006, 'bagging_temperature': 5.201494337630724, 'scale_pos_weight': 3.4654234457101696}. Best is trial 1 with value: 0.7775268271051835.
[I 2026-05-28 23:01:03,014] Trial 6 finished with value: 0.7727625235392201 and parameters: {'iterations': 1592, 'learning_rate': 0.010532936767668716, 'depth': 10, 'l2_leaf_reg': 0.3625312969525188, 'subsample': 0.7230072980626115, 'random_strength': 0.0022197893683816566, 'bagging_temperature': 3.8825827657906498, 'scale_pos_weight': 6.581172837315295}. Best is trial 1 with value: 0.7775268271051835.
[I 2026-05-28 23:01:18,947] Trial 7 finished with value: 0.7685345498632721 and parameters: {'iterations': 994, 'learning_rate': 0.05576064980641999, 'depth': 8, 'l2_leaf_reg': 0.0010789339136861357, 'subsample': 0.7746405883073334, 'random_strength': 0.007983596784156485, 'bagging_temperature': 0.9882919819639258, 'scale_pos_weight': 7.43433303675277}. Best is trial 1 with value: 0.7775268271051835.
[I 2026-05-28 23:05:50,495] Trial 8 finished with value: 0.7794215419544077 and parameters: {'iterations': 1040, 'learning_rate': 0.024438365220230893, 'depth': 10, 'l2_leaf_reg': 3.2752186728664676, 'subsample': 0.9604820969688483, 'random_strength': 0.5033301493350868, 'bagging_temperature': 5.034510073283926, 'scale_pos_weight': 1.6548514929708305}. Best is trial 8 with value: 0.7794215419544077.
[I 2026-05-28 23:06:43,297] Trial 9 finished with value: 0.7772156148876402 and parameters: {'iterations': 698, 'learning_rate': 0.0601154395259994, 'depth': 9, 'l2_leaf_reg': 1.29415060064434, 'subsample': 0.9288297748855517, 'random_strength': 7.202913627840645, 'bagging_temperature': 4.766833791312241, 'scale_pos_weight': 2.1900050026610716}. Best is trial 8 with value: 0.7794215419544077.
[I 2026-05-28 23:08:10,363] Trial 10 finished with value: 0.7742391025880401 and parameters: {'iterations': 321, 'learning_rate': 0.028459458624601926, 'depth': 10, 'l2_leaf_reg': 8.092860983660046, 'subsample': 0.8692121270296054, 'random_strength': 0.3491874736365219, 'bagging_temperature': 9.287409013406286, 'scale_pos_weight': 1.272846438327957}. Best is trial 8 with value: 0.7794215419544077.
[I 2026-05-28 23:08:48,188] Trial 11 finished with value: 0.7791243857707569 and parameters: {'iterations': 1301, 'learning_rate': 0.09130564006933241, 'depth': 5, 'l2_leaf_reg': 9.834417354491654, 'subsample': 0.6452088463873266, 'random_strength': 0.08026680558831743, 'bagging_temperature': 7.299000528129124, 'scale_pos_weight': 9.938966415766359}. Best is trial 8 with value: 0.7794215419544077.
[I 2026-05-28 23:09:39,357] Trial 12 finished with value: 0.7806646289162469 and parameters: {'iterations': 1398, 'learning_rate': 0.09347288513644332, 'depth': 4, 'l2_leaf_reg': 8.728818931795791, 'subsample': 0.999356410977387, 'random_strength': 0.15828785415834665, 'bagging_temperature': 7.438924771161358, 'scale_pos_weight': 6.742149921599653}. Best is trial 12 with value: 0.7806646289162469.
[I 2026-05-28 23:10:57,608] Trial 13 finished with value: 0.777549521483173 and parameters: {'iterations': 1553, 'learning_rate': 0.02067362056241881, 'depth': 4, 'l2_leaf_reg': 2.5430164182130324, 'subsample': 0.9982642041604975, 'random_strength': 0.22729233063752632, 'bagging_temperature': 9.894853402754686, 'scale_pos_weight': 6.182447437781355}. Best is trial 12 with value: 0.7806646289162469.
[I 2026-05-28 23:12:13,232] Trial 14 finished with value: 0.7811704535391014 and parameters: {'iterations': 1578, 'learning_rate': 0.0374638190632113, 'depth': 6, 'l2_leaf_reg': 5.302523559482853, 'subsample': 0.927660724571413, 'random_strength': 1.767490201969859, 'bagging_temperature': 6.534793161886625, 'scale_pos_weight': 7.508836282599957}. Best is trial 14 with value: 0.7811704535391014.
[I 2026-05-28 23:13:14,742] Trial 15 finished with value: 0.7776399352002928 and parameters: {'iterations': 1786, 'learning_rate': 0.036985914352634625, 'depth': 6, 'l2_leaf_reg': 0.012291008584621413, 'subsample': 0.902222143795587, 'random_strength': 2.1474161910457643, 'bagging_temperature': 8.234141723918315, 'scale_pos_weight': 7.44528589155458}. Best is trial 14 with value: 0.7811704535391014.
[I 2026-05-28 23:13:46,582] Trial 16 finished with value: 0.7789225830674689 and parameters: {'iterations': 1513, 'learning_rate': 0.09907611135468883, 'depth': 5, 'l2_leaf_reg': 0.6492780136931363, 'subsample': 0.9290723405975494, 'random_strength': 0.1429400744451079, 'bagging_temperature': 6.182896177182799, 'scale_pos_weight': 7.9244031814027185}. Best is trial 14 with value: 0.7811704535391014.
[I 2026-05-28 23:15:00,208] Trial 17 finished with value: 0.7816399236444567 and parameters: {'iterations': 1269, 'learning_rate': 0.04020992519763575, 'depth': 6, 'l2_leaf_reg': 4.878478021510978, 'subsample': 0.8388279421401803, 'random_strength': 2.3425547940848275, 'bagging_temperature': 6.4479404532221345, 'scale_pos_weight': 6.089975781296656}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:15:49,256] Trial 18 finished with value: 0.7773292437086944 and parameters: {'iterations': 1736, 'learning_rate': 0.04151474846407263, 'depth': 6, 'l2_leaf_reg': 0.0037013302811275575, 'subsample': 0.8400979362391325, 'random_strength': 2.956425179135815, 'bagging_temperature': 6.203120833189119, 'scale_pos_weight': 5.268303092044496}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:17:09,361] Trial 19 finished with value: 0.7802088974159547 and parameters: {'iterations': 1199, 'learning_rate': 0.03815406015464477, 'depth': 7, 'l2_leaf_reg': 3.0486937301963963, 'subsample': 0.8241978969058696, 'random_strength': 3.7149801261851016, 'bagging_temperature': 2.948365596905748, 'scale_pos_weight': 5.772207745570008}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:18:14,990] Trial 20 finished with value: 0.7801789770738277 and parameters: {'iterations': 1870, 'learning_rate': 0.04826143662952766, 'depth': 6, 'l2_leaf_reg': 0.6224470493726728, 'subsample': 0.8869846378027214, 'random_strength': 1.2047721509279334, 'bagging_temperature': 8.69616988377668, 'scale_pos_weight': 3.0532769470184533}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:19:06,212] Trial 21 finished with value: 0.7807095254792096 and parameters: {'iterations': 1411, 'learning_rate': 0.07899627497206647, 'depth': 4, 'l2_leaf_reg': 7.037956510338061, 'subsample': 0.9632312323804976, 'random_strength': 0.07635846002795345, 'bagging_temperature': 6.17076232100218, 'scale_pos_weight': 6.946926560189192}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:19:45,412] Trial 22 finished with value: 0.7798281005190818 and parameters: {'iterations': 1363, 'learning_rate': 0.07620264196249397, 'depth': 5, 'l2_leaf_reg': 3.644380058273761, 'subsample': 0.9409842864699363, 'random_strength': 0.06992228562196699, 'bagging_temperature': 6.231057800045655, 'scale_pos_weight': 8.146042855741827}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:20:51,920] Trial 23 finished with value: 0.7796891808235467 and parameters: {'iterations': 1189, 'learning_rate': 0.032207634073442314, 'depth': 7, 'l2_leaf_reg': 1.1398613881594166, 'subsample': 0.8964538049185401, 'random_strength': 0.007775520778487156, 'bagging_temperature': 6.0299456508534295, 'scale_pos_weight': 5.2561847236398505}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:21:32,358] Trial 24 finished with value: 0.779958931129393 and parameters: {'iterations': 1629, 'learning_rate': 0.07237266468820452, 'depth': 5, 'l2_leaf_reg': 5.257112718433258, 'subsample': 0.8097773979125019, 'random_strength': 0.9928851484476067, 'bagging_temperature': 6.807865874911997, 'scale_pos_weight': 7.05737132553379}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:23:07,121] Trial 25 finished with value: 0.77956682805961 and parameters: {'iterations': 1418, 'learning_rate': 0.01772819977563618, 'depth': 7, 'l2_leaf_reg': 1.6929757557808693, 'subsample': 0.9578472116348974, 'random_strength': 0.3091003839270481, 'bagging_temperature': 8.223688667463179, 'scale_pos_weight': 5.88065742996403}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:24:26,909] Trial 26 finished with value: 0.7813092555363065 and parameters: {'iterations': 1693, 'learning_rate': 0.045146203999430645, 'depth': 6, 'l2_leaf_reg': 5.354114850787675, 'subsample': 0.911816882788418, 'random_strength': 9.82508815353394, 'bagging_temperature': 5.591600459572647, 'scale_pos_weight': 8.398452622914231}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:25:22,597] Trial 27 finished with value: 0.779752206495942 and parameters: {'iterations': 1775, 'learning_rate': 0.046083441918569897, 'depth': 6, 'l2_leaf_reg': 0.940208667691379, 'subsample': 0.7558860036707603, 'random_strength': 4.936812354734264, 'bagging_temperature': 3.366184294230103, 'scale_pos_weight': 8.600679911840507}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:26:56,288] Trial 28 finished with value: 0.7816144651390209 and parameters: {'iterations': 1663, 'learning_rate': 0.03284841222502646, 'depth': 7, 'l2_leaf_reg': 4.577038407462739, 'subsample': 0.8682428449334717, 'random_strength': 8.706781099166781, 'bagging_temperature': 1.7769724394582354, 'scale_pos_weight': 9.167248587038115}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:28:10,235] Trial 29 finished with value: 0.7753985773695857 and parameters: {'iterations': 1959, 'learning_rate': 0.03027986321387452, 'depth': 8, 'l2_leaf_reg': 0.1905538567429709, 'subsample': 0.8589797799726222, 'random_strength': 9.725826879377106, 'bagging_temperature': 1.8725641999460632, 'scale_pos_weight': 9.391410547157452}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:28:50,882] Trial 30 finished with value: 0.7761429693740743 and parameters: {'iterations': 1729, 'learning_rate': 0.048876978008568134, 'depth': 7, 'l2_leaf_reg': 0.3003654131400989, 'subsample': 0.7206094588481433, 'random_strength': 4.240422314243469, 'bagging_temperature': 1.681268248640531, 'scale_pos_weight': 9.940510773258932}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:30:07,959] Trial 31 finished with value: 0.780590382669727 and parameters: {'iterations': 1635, 'learning_rate': 0.034931874280265326, 'depth': 6, 'l2_leaf_reg': 4.754407453204202, 'subsample': 0.9085158817000982, 'random_strength': 2.1717312865789107, 'bagging_temperature': 0.3630607628177518, 'scale_pos_weight': 9.186723539248504}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:31:05,433] Trial 32 finished with value: 0.7787117104595404 and parameters: {'iterations': 1493, 'learning_rate': 0.04242793454094753, 'depth': 7, 'l2_leaf_reg': 2.354095149453986, 'subsample': 0.8732418376692187, 'random_strength': 1.928422124308626, 'bagging_temperature': 5.404747796063632, 'scale_pos_weight': 8.257204891099999}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:31:51,078] Trial 33 finished with value: 0.7777870010469089 and parameters: {'iterations': 1273, 'learning_rate': 0.0622494123055391, 'depth': 8, 'l2_leaf_reg': 5.570645079859661, 'subsample': 0.8436396873068794, 'random_strength': 9.678162859414499, 'bagging_temperature': 4.443534600999819, 'scale_pos_weight': 8.856409361296915}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:33:37,546] Trial 34 finished with value: 0.7809637360388825 and parameters: {'iterations': 1871, 'learning_rate': 0.024437387267849744, 'depth': 6, 'l2_leaf_reg': 0.6684578567264151, 'subsample': 0.9230348485957441, 'random_strength': 5.278267357025768, 'bagging_temperature': 6.831937124069197, 'scale_pos_weight': 7.5966278478289375}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:35:07,772] Trial 35 finished with value: 0.7804659719683239 and parameters: {'iterations': 1673, 'learning_rate': 0.02743813184095155, 'depth': 5, 'l2_leaf_reg': 1.8291088832488234, 'subsample': 0.8811074309242845, 'random_strength': 0.6258784219209971, 'bagging_temperature': 5.587998441335579, 'scale_pos_weight': 9.469993204706096}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:36:11,438] Trial 36 finished with value: 0.7806549598201084 and parameters: {'iterations': 1868, 'learning_rate': 0.054016722023782916, 'depth': 6, 'l2_leaf_reg': 3.976438804646851, 'subsample': 0.8202684554291091, 'random_strength': 2.003687580683987, 'bagging_temperature': 3.6687144734853803, 'scale_pos_weight': 8.510908481291334}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:37:49,117] Trial 37 finished with value: 0.777998797408397 and parameters: {'iterations': 1475, 'learning_rate': 0.01904947614330612, 'depth': 7, 'l2_leaf_reg': 0.0848653860293314, 'subsample': 0.8361684459701354, 'random_strength': 5.861745800627396, 'bagging_temperature': 6.807754157050976, 'scale_pos_weight': 7.945510557268794}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:38:41,297] Trial 38 finished with value: 0.7786658330771611 and parameters: {'iterations': 1076, 'learning_rate': 0.033739603387879305, 'depth': 6, 'l2_leaf_reg': 0.021187973978619476, 'subsample': 0.7711392402481076, 'random_strength': 1.2510326097209106, 'bagging_temperature': 8.08247400036524, 'scale_pos_weight': 4.603430881854703}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:39:49,378] Trial 39 finished with value: 0.7797990504312735 and parameters: {'iterations': 922, 'learning_rate': 0.04091223387404404, 'depth': 8, 'l2_leaf_reg': 9.988297502102071, 'subsample': 0.9780573276530881, 'random_strength': 3.1057667300339786, 'bagging_temperature': 5.562775114351966, 'scale_pos_weight': 6.253771171655861}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:40:34,927] Trial 40 finished with value: 0.7748689027851383 and parameters: {'iterations': 1304, 'learning_rate': 0.0656819947026444, 'depth': 9, 'l2_leaf_reg': 2.4326308734576654, 'subsample': 0.7963011208543881, 'random_strength': 6.752756546678203, 'bagging_temperature': 4.2450994497802625, 'scale_pos_weight': 7.213633193488217}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:42:25,024] Trial 41 finished with value: 0.7806566717958172 and parameters: {'iterations': 1874, 'learning_rate': 0.021722506765160434, 'depth': 6, 'l2_leaf_reg': 0.7408543040266516, 'subsample': 0.9223626065836716, 'random_strength': 4.642414427137181, 'bagging_temperature': 6.806973359960741, 'scale_pos_weight': 7.876045373885292}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:44:08,051] Trial 42 finished with value: 0.7801279138316973 and parameters: {'iterations': 1947, 'learning_rate': 0.024414591943096337, 'depth': 5, 'l2_leaf_reg': 0.4456067490545248, 'subsample': 0.9127800827606561, 'random_strength': 8.751645487463634, 'bagging_temperature': 4.855942069655434, 'scale_pos_weight': 7.607620431722422}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:45:40,465] Trial 43 finished with value: 0.7804878353247713 and parameters: {'iterations': 1669, 'learning_rate': 0.027705469289252594, 'depth': 6, 'l2_leaf_reg': 1.524566456513655, 'subsample': 0.9377329470730559, 'random_strength': 2.807878792390364, 'bagging_temperature': 7.742383529634088, 'scale_pos_weight': 8.913197416506616}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:46:24,850] Trial 44 finished with value: 0.7772267712626757 and parameters: {'iterations': 1838, 'learning_rate': 0.03168680136521659, 'depth': 7, 'l2_leaf_reg': 0.21082058056124764, 'subsample': 0.8614538713644087, 'random_strength': 0.0012822014689742767, 'bagging_temperature': 6.912659444241994, 'scale_pos_weight': 8.375789127132432}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:47:39,724] Trial 45 finished with value: 0.7810757848490221 and parameters: {'iterations': 1556, 'learning_rate': 0.0375265679582593, 'depth': 7, 'l2_leaf_reg': 5.643596771601716, 'subsample': 0.8872443695707819, 'random_strength': 5.8692571193809995, 'bagging_temperature': 5.882325658461109, 'scale_pos_weight': 6.348561677976338}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:48:22,503] Trial 46 finished with value: 0.778732279134358 and parameters: {'iterations': 1573, 'learning_rate': 0.05205170277881906, 'depth': 8, 'l2_leaf_reg': 5.93571417318287, 'subsample': 0.8885488133145044, 'random_strength': 1.3953614236418785, 'bagging_temperature': 5.608734979220635, 'scale_pos_weight': 6.481638266616996}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:49:13,048] Trial 47 finished with value: 0.7800746107546813 and parameters: {'iterations': 725, 'learning_rate': 0.03744297975827482, 'depth': 7, 'l2_leaf_reg': 4.3806728303884315, 'subsample': 0.9455116263745995, 'random_strength': 0.8909276623620557, 'bagging_temperature': 5.024378333828174, 'scale_pos_weight': 5.083626341783386}. Best is trial 17 with value: 0.7816399236444567.
[I 2026-05-28 23:49:36,164] Trial 48 finished with value: 0.7758853027634389 and parameters: {'iterations': 336, 'learning_rate': 0.04191720023701538, 'depth': 7, 'l2_leaf_reg': 2.2751606667490565, 'subsample': 0.8566722602450971, 'random_strength': 0.5344961691695237, 'bagging_temperature': 4.605535842869631, 'scale_pos_weight': 6.743310769873199}. Best is trial 17 with value: 0.7816399236444567.

In [ ]:
cat_study.best_params

{'iterations': 1825,
 'learning_rate': 0.03480089433662196,
 'depth': 5,
 'l2_leaf_reg': 9.975131167809268,
 'subsample': 0.9944006706987512,
 'random_strength': 1.0556500215634455,
 'bagging_temperature': 4.6402150694429505,
 'scale_pos_weight': 5.255271095208505}

In [ ]:
cat_study.best_value

0.7821605461573439

In [ ]:
# =========================================
# FINAL TUNED CATBOOST MODEL
# =========================================
cat_model = CatBoostClassifier(
    **cat_study.best_params,
    loss_function='Logloss',
    eval_metric='AUC',
    random_state=42,
    verbose=100
)

# =========================================
# TRAIN MODEL
# =========================================

cat_model.fit(

    X_train,
    y_train,

    eval_set=(X_val, y_val),

    early_stopping_rounds=50,

    verbose=False
)

# =========================================
# PREDICTIONS
# =========================================

cat_pred = cat_model.predict_proba(X_val)[:,1]

# =========================================
# ROC-AUC SCORE
# =========================================

cat_auc = roc_auc_score(y_val,cat_pred)

print("CatBoost ROC-AUC :", cat_auc)

CatBoost ROC-AUC : 0.7821605461573439

In [40]:
feature_imp = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': cat_model.feature_importances_
}).sort_values(
    by='Importance',
    ascending=False
)

feature_imp.tail(50)

                         Feature  Importance
45     AMT_REQ_CREDIT_BUREAU_MON    0.195066
22                    FLAG_PHONE    0.189384
137        CC_LATE_PAYMENT_RATIO    0.179224
59           CLOSED_CREDIT_COUNT    0.175449
37      OBS_30_CNT_SOCIAL_CIRCLE    0.174622
9                NAME_TYPE_SUITE    0.168558
139         MAX_DRAWINGS_CURRENT    0.159432
0             NAME_CONTRACT_TYPE    0.159013
84       OVERDUE_PER_ACTIVE_LOAN    0.151397
89               CANCELLED_COUNT    0.150473
26          REGION_RATING_CLIENT    0.132963
86       TOTAL_PREV_APPLICATIONS    0.130455
55             MAX_BUREAU_STATUS    0.111763
151                  AVG_POS_DPD    0.095882
56             AVG_BUREAU_STATUS    0.086110
25               CNT_FAM_MEMBERS    0.084419
67                   MAX_OVERDUE    0.083901
135                   AVG_CC_DPD    0.081920
23                    FLAG_EMAIL    0.078235
136                   MAX_CC_DPD    0.075689
44    AMT_REQ_CREDIT_BUREAU_WEEK    0.072445
66                 TOTAL_OVERDUE    0.065743
118             DPD_OVER_30_MEAN    0.064953
131                 MAX_CC_LIMIT    0.060636
43     AMT_REQ_CREDIT_BUREAU_DAY    0.055886
68                   HAS_OVERDUE    0.051325
42    AMT_REQ_CREDIT_BUREAU_HOUR    0.045574
30    REG_REGION_NOT_LIVE_REGION    0.045566
78          AVG_SEVERE_DPD_RATIO    0.045280
50         IS_HIGH_RISK_BUILDING    0.040592
120              DPD_OVER_30_STD    0.038886
123              DPD_OVER_60_STD    0.031747
70        MAX_CREDIT_DAY_OVERDUE    0.031622
124             DPD_OVER_90_MEAN    0.031461
69        AVG_CREDIT_DAY_OVERDUE    0.031173
3                FLAG_OWN_REALTY    0.030671
52         IS_LOW_RISK_HOUSETYPE    0.030199
49             HAS_BUILDING_INFO    0.028868
82       OVERDUE_TO_CREDIT_RATIO    0.017276
35       LIVE_CITY_NOT_WORK_CITY    0.017206
34        REG_CITY_NOT_WORK_CITY    0.015853
121             DPD_OVER_60_MEAN    0.014159
125              DPD_OVER_90_MAX    0.010539
126              DPD_OVER_90_STD    0.006790
21              FLAG_CONT_MOBILE    0.000000
32   LIVE_REGION_NOT_WORK_REGION    0.000000
76               HAS_DPD_HISTORY    0.000000
31    REG_REGION_NOT_WORK_REGION    0.000000
122              DPD_OVER_60_MAX    0.000000
119              DPD_OVER_30_MAX    0.000000

### checking if dropping 0 importance in both models improves performance

In [41]:
col_to_drop = feature_imp[feature_imp['Importance'] == 0]['Feature'].tolist()
X_train_reduced = X_train.drop(columns=col_to_drop)
X_val_reduced = X_val.drop(columns=col_to_drop)

In [42]:
cat_model.fit(

    X_train_reduced,
    y_train,

    eval_set=(X_val_reduced, y_val),

    early_stopping_rounds=50,

    verbose=False
)
cat_pred = cat_model.predict_proba(X_val_reduced)[:,1]
cat_auc = roc_auc_score(y_val,cat_pred)

print("CatBoost ROC-AUC :", cat_auc)

CatBoost ROC-AUC : 0.7813902355539477

### instead of helping it actually made it drop the roc_auc, so we will keep all features for the final model

### ensemble on two models
ensemble_pred = 0.5 * cat_pred + 0.5 * lgb_pred

In [43]:
blend_pred = (
    0.5 * lgb_pred
    +
    0.5 * cat_pred
)

In [ ]:
blend_auc = roc_auc_score(y_val,blend_pred)

print("Blended ROC-AUC :", blend_auc)

Blended ROC-AUC : 0.7824372085651143

### FINAL xgboost model

In [ ]:
# =========================================
# XGBOOST MODEL
# =========================================
xgb_model = XGBClassifier(
    objective='binary:logistic',
    eval_metric='auc',
    n_estimators=1000,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.1,
    reg_lambda=0.1,
    scale_pos_weight=(
        y_train.value_counts()[0]
        /
        y_train.value_counts()[1]
    ),
    random_state=42,
    n_jobs=-1
)

# =========================================
# TRAIN XGBOOST
# =========================================

xgb_model.fit(

    X_train,
    y_train,

    eval_set=[(X_val, y_val)],

    verbose=False
)

# =========================================
# XGBOOST PREDICTIONS
# =========================================

xgb_pred = xgb_model.predict_proba(X_val)[:,1]

# =========================================
# XGBOOST ROC-AUC
# =========================================

xgb_auc = roc_auc_score(y_val,xgb_pred)

print("XGBoost ROC-AUC :", xgb_auc)

XGBoost ROC-AUC : 0.7706375461738573

In [ ]:
# =========================================
# TRIPLE ENSEMBLE
# =========================================

ensemble_pred_prob = (
    0.5 * cat_pred
    +
    0.3 * lgb_pred
    +
    0.2 * xgb_pred
)

# =========================================
# ENSEMBLE ROC-AUC
# =========================================

ensemble_auc = roc_auc_score(y_val,ensemble_pred_prob)

print("Triple Ensemble ROC-AUC :", ensemble_auc)

Triple Ensemble ROC-AUC : 0.7824745011026373

In [50]:
ensemble_pred = (ensemble_pred_prob >= 0.5).astype(int)

In [51]:
print(classification_report(y_val,ensemble_pred))

              precision    recall  f1-score   support

           0       0.95      0.86      0.91     56505
           1       0.24      0.50      0.33      4962

    accuracy                           0.83     61467
   macro avg       0.60      0.68      0.62     61467
weighted avg       0.89      0.83      0.86     61467

In [52]:
print(confusion_matrix(y_val,ensemble_pred))

[[48801  7704]
 [ 2472  2490]]

### threshold tuning

In [53]:
thresholds = np.arange(0.10, 0.91, 0.01)

results = []

for threshold in thresholds:

    pred = (ensemble_pred_prob >= threshold).astype(int)
    f1 = f1_score(y_val,pred)
    results.append([threshold, f1])

results = pd.DataFrame(
    results,
    columns=['Threshold', 'F1']
)

results.sort_values(by='F1',ascending=False).head(10)

    Threshold        F1
45       0.55  0.335284
44       0.54  0.334817
46       0.56  0.334301
47       0.57  0.334139
43       0.53  0.333771
42       0.52  0.332065
49       0.59  0.332058
48       0.58  0.331954
41       0.51  0.331062
50       0.60  0.330301

In [54]:
best_threshold = 0.55

final_pred = (ensemble_pred_prob >= best_threshold).astype(int)

print(classification_report(y_val,final_pred))
print(confusion_matrix(y_val,final_pred))

              precision    recall  f1-score   support

           0       0.95      0.90      0.92     56505
           1       0.27      0.43      0.34      4962

    accuracy                           0.86     61467
   macro avg       0.61      0.67      0.63     61467
weighted avg       0.89      0.86      0.88     61467

[[50802  5703]
 [ 2814  2148]]

### final model comparison

In [56]:
comparison = pd.DataFrame({

    'Model':[
        'LightGBM',
        'CatBoost',
        'XGBoost',
        'Triple Ensemble'
    ],

    'ROC_AUC':[
        lgb_auc,
        cat_auc,
        xgb_auc,
        ensemble_auc
    ]
})

comparison.sort_values(
    by='ROC_AUC',
    ascending=False
)

             Model   ROC_AUC
3  Triple Ensemble  0.782475
1         CatBoost  0.781390
0         LightGBM  0.780350
2          XGBoost  0.770638

# Retrain models on full training data

In [ ]:
lgb_final = lgb.LGBMClassifier(
    n_estimators      = 1756,
    learning_rate     = 0.01331366272815625,
    num_leaves        = 74,
    max_depth         = 12,
    min_child_samples = 50,
    subsample         = 0.8567488572903952,
    colsample_bytree  = 0.6144388426493165,
    reg_alpha         = 9.928108621631159,
    reg_lambda        = 3.2730873799027798,
    class_weight      = "balanced",   # handles class imbalance
    random_state      = 42,
    n_jobs            = -1,
    verbose           = -1,
)

cat_final = CatBoostClassifier(
    loss_function='Logloss',
    eval_metric='AUC',
    iterations=1825,
    learning_rate=0.03480089433662196,
    depth=5,
    l2_leaf_reg=9.975131167809268,
    subsample=0.9944006706987512,
    random_strength=1.0556500215634455,
    bagging_temperature=4.6402150694429505,
    scale_pos_weight=5.255271095208505,
    random_state=42,
    verbose=100
)

xgb_final = XGBClassifier(
    objective='binary:logistic',
    eval_metric='auc',
    n_estimators=1000,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.1,
    reg_lambda=0.1,
    scale_pos_weight=(
        y.value_counts()[0]
        /
        y.value_counts()[1]
    ),
    random_state=42,
    n_jobs=-1
)

In [66]:
cat_final.fit(X, y,verbose=False)
lgb_final.fit(X, y)
xgb_final.fit(X, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='auc', feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=1000,
              n_jobs=-1, num_parallel_tree=None, ...)

In [70]:
ensemble_info = {

    'cat_weight': 0.5,

    'lgb_weight': 0.3,

    'xgb_weight': 0.2,

    'threshold': 0.5
}

In [ ]:
model_metrics = {
    "roc_auc": ensemble_auc,
    "cat_weight": 0.5,
    "lgb_weight": 0.3,
    "xgb_weight": 0.2,
    "threshold": 0.5
}

## Exporting the models ,encoders and ensemble info

In [ ]:
model_export_path = Path("../streamlit/models")
if not model_export_path.exists():
    root = Tk()
    root.withdraw()
    model_export_path = Path(askdirectory(title="Select the directory containing the cleaned data"))

In [ ]:
joblib.dump(cat_final,model_export_path/'catboost_model.pkl')

joblib.dump(lgb_final,model_export_path/'lightgbm_model.pkl')

joblib.dump(xgb_final,model_export_path/'xgboost_model.pkl')

joblib.dump(encoders,model_export_path/'encoders.pkl')

joblib.dump(X.columns.tolist(),model_export_path/'feature_columns.pkl')

joblib.dump(ensemble_info,model_export_path/'ensemble_info.pkl')

joblib.dump(model_metrics,model_export_path / "model_metrics.pkl")

['../streamlit/models/ensemble_info.pkl']