## Library imports

In [28]:
# libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import os
from pathlib import Path
from tkinter import Tk
from tkinter.filedialog import askdirectory

# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score

# Models
import lightgbm as lgb
from catboost import CatBoostClassifier
from xgboost import XGBClassifier

# Hyperparameter tuning
from sklearn.model_selection import StratifiedKFold
import optuna

# exporting the model
import joblib

## Load the dataset

In [29]:
cleaned_data_path = Path("../streamlit/cleaned_data")
if not cleaned_data_path.exists():
    root = Tk()
    root.withdraw()
    cleaned_data_path = Path(askdirectory(title="Select the directory containing the cleaned data"))

In [30]:
train=pd.read_parquet(cleaned_data_path/'train_final.parquet')
test=pd.read_parquet(cleaned_data_path/'test_final.parquet')

In [31]:
for col in train.columns:
    print(col)

SK_ID_CURR
TARGET
NAME_CONTRACT_TYPE
CODE_GENDER
FLAG_OWN_CAR
FLAG_OWN_REALTY
CNT_CHILDREN
AMT_INCOME_TOTAL
AMT_CREDIT
AMT_ANNUITY
AMT_GOODS_PRICE
NAME_TYPE_SUITE
NAME_INCOME_TYPE
NAME_EDUCATION_TYPE
NAME_FAMILY_STATUS
NAME_HOUSING_TYPE
REGION_POPULATION_RELATIVE
DAYS_BIRTH
DAYS_EMPLOYED
DAYS_REGISTRATION
DAYS_ID_PUBLISH
FLAG_EMP_PHONE
FLAG_WORK_PHONE
FLAG_CONT_MOBILE
FLAG_PHONE
FLAG_EMAIL
OCCUPATION_TYPE
CNT_FAM_MEMBERS
REGION_RATING_CLIENT
REGION_RATING_CLIENT_W_CITY
WEEKDAY_APPR_PROCESS_START
HOUR_APPR_PROCESS_START
REG_REGION_NOT_LIVE_REGION
REG_REGION_NOT_WORK_REGION
LIVE_REGION_NOT_WORK_REGION
REG_CITY_NOT_LIVE_CITY
REG_CITY_NOT_WORK_CITY
LIVE_CITY_NOT_WORK_CITY
ORGANIZATION_TYPE
OBS_30_CNT_SOCIAL_CIRCLE
DEF_30_CNT_SOCIAL_CIRCLE
OBS_60_CNT_SOCIAL_CIRCLE
DEF_60_CNT_SOCIAL_CIRCLE
DAYS_LAST_PHONE_CHANGE
AMT_REQ_CREDIT_BUREAU_HOUR
AMT_REQ_CREDIT_BUREAU_DAY
AMT_REQ_CREDIT_BUREAU_WEEK
AMT_REQ_CREDIT_BUREAU_MON
AMT_REQ_CREDIT_BUREAU_QRT
AMT_REQ_CREDIT_BUREAU_YEAR
EXT_SOURCE_MEAN
HAS_BUILDING_INFO
IS_HIGH_RISK_BUILDING
WALL_RISK
IS_LOW_RISK_HOUSETYPE
TOTAL_DOCUMENTS
LOAN_TO_INCOME
TOTAL_PREV_APPLICATIONS
APPROVED_COUNT
REFUSED_COUNT
CANCELLED_COUNT
AVG_PREV_CREDIT
MAX_PREV_CREDIT
AVG_PREV_APPLICATION
AVG_GOODS_PRICE
AVG_PREV_ANNUITY
MAX_PREV_ANNUITY
AVG_CNT_PAYMENT
MAX_CNT_PAYMENT
AVG_DAYS_DECISION
MIN_DAYS_DECISION
MAX_DAYS_DECISION
AVG_DAYS_LAST_DUE_MISSING
AVG_INSURED_MISSING
MAX_BUREAU_STATUS
AVG_BUREAU_STATUS
TOTAL_BUREAU_LOANS
ACTIVE_CREDIT_COUNT
CLOSED_CREDIT_COUNT
TOTAL_DEBT
AVG_DEBT
MAX_DEBT
TOTAL_CREDIT_SUM
AVG_CREDIT_SUM
MAX_CREDIT_SUM
TOTAL_OVERDUE
MAX_OVERDUE
HAS_OVERDUE
AVG_CREDIT_DAY_OVERDUE
MAX_CREDIT_DAY_OVERDUE
AVG_DAYS_CREDIT
MIN_DAYS_CREDIT
MAX_DAYS_CREDIT
AVG_DAYS_CREDIT_ENDDATE
AVG_DAYS_CREDIT_UPDATE
HAS_DPD_HISTORY
AVG_DPD_RATIO
AVG_SEVERE_DPD_RATIO
AVG_CLOSED_RATIO
AVG_MONTHS_HISTORY
ACTIVE_DEBT_RATIO
OVERDUE_TO_CREDIT_RATIO
CLOSED_TO_TOTAL_RATIO
OVERDUE_PER_ACTIVE_LOAN
DEBT_PER_ACTIVE_LOAN
TOTAL_INSTALLMENTS
AVG_PAYMENT_DELAY
STD_PAYMENT_DELAY
MAX_PAYMENT_DELAY
AVG_PAYMENT_RATIO
MIN_PAYMENT_RATIO
INSTALLMENT_LATE_PAYMENT_RATIO
PAYMENT_RATIO_STD
UNDER_PAYMENT_RATIO
AVG_AMT_PAYMENT
MAX_AMT_PAYMENT
AVG_AMT_INSTALMENT
MAX_AMT_INSTALMENT
AVG_DAYS_INSTALMENT
AVG_DAYS_ENTRY_PAYMENT
DPD_OVER_30_MEAN
DPD_OVER_30_MAX
DPD_OVER_30_STD
DPD_OVER_60_MEAN
DPD_OVER_60_MAX
DPD_OVER_60_STD
DPD_OVER_90_MEAN
DPD_OVER_90_MAX
DPD_OVER_90_STD
TOTAL_CC_LOANS
AVG_CC_BALANCE
MAX_CC_BALANCE
AVG_CC_LIMIT
MAX_CC_LIMIT
AVG_LIMIT_USAGE_RATIO
MAX_LIMIT_USAGE_RATIO
MIN_CC_PAYMENT_RATIO
AVG_CC_DPD
MAX_CC_DPD
CC_LATE_PAYMENT_RATIO
AVG_DRAWINGS_CURRENT
MAX_DRAWINGS_CURRENT
AVG_PAYMENT_CURRENT
AVG_RECEIVABLE
CC_AVG_MONTHS_BALANCE
TOTAL_POS_LOANS
POS_AVG_MONTHS_BALANCE
MIN_MONTHS_BALANCE
MAX_MONTHS_BALANCE
AVG_CNT_INSTALMENT
MAX_CNT_INSTALMENT
AVG_CNT_INSTALMENT_FUTURE
MAX_CNT_INSTALMENT_FUTURE
AVG_POS_DPD
MAX_POS_DPD
AVG_POS_DPD_DEF
MAX_POS_DPD_DEF
LATE_PAYMENT_RATIO
LATE_PAYMENT_DEF_RATIO

### target separation

In [32]:
X = train.drop(columns=['SK_ID_CURR', 'TARGET'])
y = train['TARGET']

In [33]:
for col in X.select_dtypes(include='category').columns:
        X[col] = X[col].astype(str)

### endoding categorical features

In [34]:
cat_cols = X.select_dtypes(include='object').columns

len(cat_cols)

12

In [35]:
cat_cols

Index(['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY',
       'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE',
       'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE'],
      dtype='object')

In [36]:
encoders = {}
for col in cat_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])
    encoders[col] = le

### split the data into training and validation sets

In [37]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2,stratify= y ,random_state=42)

# model testing

### base model testing

In [38]:
model = lgb.LGBMClassifier(
    n_estimators      = 1000,
    learning_rate     = 0.05,
    num_leaves        = 63,
    max_depth         = -1,
    min_child_samples = 50,
    subsample         = 0.8,
    colsample_bytree  = 0.8,
    reg_alpha         = 0.1,
    reg_lambda        = 0.1,
    class_weight      = "balanced",   # handles class imbalance
    random_state      = 42,
    n_jobs            = -1,
    verbose           = -1,
)

model.fit(
    X_train, y_train,
    eval_set              = [(X_val, y_val)],
    callbacks             = [lgb.early_stopping(50, verbose=False),
                                lgb.log_evaluation(period=-1)],
)

pred_prob = model.predict_proba(X_val)[:, 1]
auc       = roc_auc_score(y_val, pred_prob)

In [39]:
auc

np.float64(0.7670645797540111)

In [40]:
pred = model.predict(X_val)

confusion_matrix(y_val, pred)

array([[47946,  8559],
       [ 2466,  2496]])

In [41]:
print(classification_report(y_val,pred))

              precision    recall  f1-score   support

           0       0.95      0.85      0.90     56505
           1       0.23      0.50      0.31      4962

    accuracy                           0.82     61467
   macro avg       0.59      0.68      0.60     61467
weighted avg       0.89      0.82      0.85     61467

In [42]:
feature_imp = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': model.feature_importances_
}).sort_values(
    by='Importance',
    ascending=False
)

feature_imp.tail(50)

                         Feature  Importance
154              MAX_POS_DPD_DEF         116
4                   CNT_CHILDREN         115
27   REGION_RATING_CLIENT_W_CITY         106
13             NAME_HOUSING_TYPE         101
141               AVG_RECEIVABLE         101
38      DEF_30_CNT_SOCIAL_CIRCLE         100
135                   AVG_CC_DPD          99
45     AMT_REQ_CREDIT_BUREAU_MON          97
40      DEF_60_CNT_SOCIAL_CIRCLE          80
20               FLAG_WORK_PHONE          79
137        CC_LATE_PAYMENT_RATIO          78
26          REGION_RATING_CLIENT          76
22                    FLAG_PHONE          75
33        REG_CITY_NOT_LIVE_CITY          64
118             DPD_OVER_30_MEAN          60
3                FLAG_OWN_REALTY          53
120              DPD_OVER_30_STD          53
35       LIVE_CITY_NOT_WORK_CITY          49
0             NAME_CONTRACT_TYPE          48
34        REG_CITY_NOT_WORK_CITY          41
87        MAX_CREDIT_DAY_OVERDUE          40
72             MAX_BUREAU_STATUS          40
83                 TOTAL_OVERDUE          34
101      OVERDUE_PER_ACTIVE_LOAN          34
23                    FLAG_EMAIL          32
52         IS_LOW_RISK_HOUSETYPE          31
44    AMT_REQ_CREDIT_BUREAU_WEEK          26
50         IS_HIGH_RISK_BUILDING          25
95          AVG_SEVERE_DPD_RATIO          25
136                   MAX_CC_DPD          24
49             HAS_BUILDING_INFO          23
84                   MAX_OVERDUE          23
99       OVERDUE_TO_CREDIT_RATIO          18
121             DPD_OVER_60_MEAN          17
32   LIVE_REGION_NOT_WORK_REGION          16
123              DPD_OVER_60_STD          16
124             DPD_OVER_90_MEAN          15
30    REG_REGION_NOT_LIVE_REGION          13
86        AVG_CREDIT_DAY_OVERDUE          12
31    REG_REGION_NOT_WORK_REGION          11
43     AMT_REQ_CREDIT_BUREAU_DAY           8
93               HAS_DPD_HISTORY           8
126              DPD_OVER_90_STD           7
42    AMT_REQ_CREDIT_BUREAU_HOUR           6
19                FLAG_EMP_PHONE           3
21              FLAG_CONT_MOBILE           1
85                   HAS_OVERDUE           0
119              DPD_OVER_30_MAX           0
122              DPD_OVER_60_MAX           0
125              DPD_OVER_90_MAX           0

In [43]:
cv = StratifiedKFold(n_splits=5,shuffle=True,random_state=42)

In [44]:
cv_scores = cross_val_score(model,X,y,scoring='roc_auc',cv=cv,n_jobs=-1)

In [45]:
print(cv_scores)
print(cv_scores.mean())
print(cv_scores.std())

[0.77372652 0.77600069 0.76064352 0.76941889 0.77184689]
0.7703273018279407
0.005303810543844025

## hyperparameter tuning with optuna for lightgbm

In [46]:
def objective(trial):
    params={
        'objective': 'binary',
        'metric': 'auc',
        'boosting_type': 'gbdt',
        'class_weight': 'balanced',
        'n_estimators': trial.suggest_int('n_estimators', 300,2000),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 20, 150),
        'max_depth': trial.suggest_int('max_depth', 3, 15),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-3, 10.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-3, 10.0, log=True),
        'random_state': 42,
        'n_jobs': -1,
        'verbose': -1,
    }
    model = lgb.LGBMClassifier(**params)
    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        callbacks=[lgb.early_stopping(50, verbose=False)],
    )
    pred_prob = model.predict_proba(X_val)[:, 1]
    auc = roc_auc_score(y_val, pred_prob)
    return auc

In [47]:
lgb_study = optuna.create_study(direction='maximize')
lgb_study.optimize(objective, n_trials=50)

[I 2026-06-02 12:52:54,447] A new study created in memory with name: no-name-888ecdf1-44ab-41b8-8398-b04ca93b0f92
[I 2026-06-02 12:53:16,485] Trial 0 finished with value: 0.7758949575931134 and parameters: {'n_estimators': 1845, 'learning_rate': 0.02525387364808817, 'num_leaves': 135, 'max_depth': 15, 'subsample': 0.8510968395039753, 'colsample_bytree': 0.8682555266107059, 'reg_alpha': 0.2681770635886934, 'reg_lambda': 0.07404719273299806}. Best is trial 0 with value: 0.7758949575931134.
[I 2026-06-02 12:53:55,459] Trial 1 finished with value: 0.7788267730602504 and parameters: {'n_estimators': 939, 'learning_rate': 0.01797643542324466, 'num_leaves': 90, 'max_depth': 12, 'subsample': 0.7755958823745761, 'colsample_bytree': 0.9723022590813227, 'reg_alpha': 7.469654869979819, 'reg_lambda': 1.1370118506683138}. Best is trial 1 with value: 0.7788267730602504.
[I 2026-06-02 12:54:08,160] Trial 2 finished with value: 0.7770847379113204 and parameters: {'n_estimators': 1619, 'learning_rate': 0.041297917649391135, 'num_leaves': 45, 'max_depth': 11, 'subsample': 0.9353627755228913, 'colsample_bytree': 0.8985353932608471, 'reg_alpha': 0.5542961098527976, 'reg_lambda': 0.005793531409308554}. Best is trial 1 with value: 0.7788267730602504.
[I 2026-06-02 12:54:40,907] Trial 3 finished with value: 0.7762514373016894 and parameters: {'n_estimators': 1254, 'learning_rate': 0.019793802185369413, 'num_leaves': 138, 'max_depth': 12, 'subsample': 0.8573705037616369, 'colsample_bytree': 0.9413377393088341, 'reg_alpha': 1.4541883000219484, 'reg_lambda': 0.0447821028558264}. Best is trial 1 with value: 0.7788267730602504.
[I 2026-06-02 12:54:59,430] Trial 4 finished with value: 0.7741572951154729 and parameters: {'n_estimators': 818, 'learning_rate': 0.0145988183312723, 'num_leaves': 54, 'max_depth': 5, 'subsample': 0.7340316410851552, 'colsample_bytree': 0.986640593341444, 'reg_alpha': 0.1840302400763867, 'reg_lambda': 8.31537458217499}. Best is trial 1 with value: 0.7788267730602504.
[I 2026-06-02 12:55:23,220] Trial 5 finished with value: 0.7765167578703893 and parameters: {'n_estimators': 1415, 'learning_rate': 0.020668731608345068, 'num_leaves': 73, 'max_depth': 6, 'subsample': 0.9343181743988145, 'colsample_bytree': 0.8141570763222433, 'reg_alpha': 0.0026736091605408224, 'reg_lambda': 0.328413012384197}. Best is trial 1 with value: 0.7788267730602504.
[I 2026-06-02 12:55:32,817] Trial 6 finished with value: 0.7775525566734398 and parameters: {'n_estimators': 1425, 'learning_rate': 0.06033698810764096, 'num_leaves': 39, 'max_depth': 10, 'subsample': 0.9382319352958035, 'colsample_bytree': 0.7547833627415275, 'reg_alpha': 0.005758874487996329, 'reg_lambda': 4.22054176901392}. Best is trial 1 with value: 0.7788267730602504.
[I 2026-06-02 12:55:55,682] Trial 7 finished with value: 0.7764742473735706 and parameters: {'n_estimators': 1035, 'learning_rate': 0.030472510656882536, 'num_leaves': 96, 'max_depth': 13, 'subsample': 0.8930645971738113, 'colsample_bytree': 0.9434403188190124, 'reg_alpha': 0.011508710752509446, 'reg_lambda': 0.5082050465469393}. Best is trial 1 with value: 0.7788267730602504.
[I 2026-06-02 12:56:08,257] Trial 8 finished with value: 0.776794458163433 and parameters: {'n_estimators': 704, 'learning_rate': 0.055965021077342594, 'num_leaves': 111, 'max_depth': 13, 'subsample': 0.8123071475571673, 'colsample_bytree': 0.6710604236982979, 'reg_alpha': 5.276114832663764, 'reg_lambda': 0.033262613717023555}. Best is trial 1 with value: 0.7788267730602504.
[I 2026-06-02 12:56:29,976] Trial 9 finished with value: 0.7776256295032762 and parameters: {'n_estimators': 1861, 'learning_rate': 0.020705118248325566, 'num_leaves': 34, 'max_depth': 9, 'subsample': 0.7832009190013857, 'colsample_bytree': 0.7329790948374689, 'reg_alpha': 0.04873323092582243, 'reg_lambda': 0.1590344462615622}. Best is trial 1 with value: 0.7788267730602504.
[I 2026-06-02 12:56:36,433] Trial 10 finished with value: 0.75199368666158 and parameters: {'n_estimators': 397, 'learning_rate': 0.01107654401687423, 'num_leaves': 71, 'max_depth': 3, 'subsample': 0.6054807559108267, 'colsample_bytree': 0.6155037337157827, 'reg_alpha': 6.088594392460402, 'reg_lambda': 1.5840813772614237}. Best is trial 1 with value: 0.7788267730602504.
[I 2026-06-02 12:57:05,215] Trial 11 finished with value: 0.7770313135693585 and parameters: {'n_estimators': 1965, 'learning_rate': 0.014316919490443857, 'num_leaves': 28, 'max_depth': 8, 'subsample': 0.7339816251024256, 'colsample_bytree': 0.763920579113016, 'reg_alpha': 0.02832603349616005, 'reg_lambda': 0.545942650218322}. Best is trial 1 with value: 0.7788267730602504.
[I 2026-06-02 12:57:11,132] Trial 12 finished with value: 0.7719708132394641 and parameters: {'n_estimators': 932, 'learning_rate': 0.0945100253279479, 'num_leaves': 102, 'max_depth': 8, 'subsample': 0.736916553516866, 'colsample_bytree': 0.7008020543369308, 'reg_alpha': 0.05183271369748672, 'reg_lambda': 0.011355238331754055}. Best is trial 1 with value: 0.7788267730602504.
[I 2026-06-02 12:57:30,352] Trial 13 finished with value: 0.7763305805120598 and parameters: {'n_estimators': 513, 'learning_rate': 0.017169302980872266, 'num_leaves': 69, 'max_depth': 9, 'subsample': 0.6554557957906181, 'colsample_bytree': 0.8271736137805374, 'reg_alpha': 1.2392488702697706, 'reg_lambda': 0.19911812746896568}. Best is trial 1 with value: 0.7788267730602504.
[I 2026-06-02 12:58:09,211] Trial 14 finished with value: 0.777343207010569 and parameters: {'n_estimators': 1187, 'learning_rate': 0.010676526340137365, 'num_leaves': 116, 'max_depth': 15, 'subsample': 0.780864186652088, 'colsample_bytree': 0.7165965583902321, 'reg_alpha': 0.0012309639638487585, 'reg_lambda': 0.0017042905953778085}. Best is trial 1 with value: 0.7788267730602504.
[I 2026-06-02 12:58:25,797] Trial 15 finished with value: 0.7759817369284681 and parameters: {'n_estimators': 1686, 'learning_rate': 0.02710574715286388, 'num_leaves': 88, 'max_depth': 7, 'subsample': 0.685446652216055, 'colsample_bytree': 0.8569449222195334, 'reg_alpha': 0.07622530712505372, 'reg_lambda': 1.450155697267061}. Best is trial 1 with value: 0.7788267730602504.
[I 2026-06-02 12:58:38,111] Trial 16 finished with value: 0.7771057809460741 and parameters: {'n_estimators': 608, 'learning_rate': 0.03838011937300056, 'num_leaves': 26, 'max_depth': 10, 'subsample': 0.805582967625715, 'colsample_bytree': 0.6081614359166322, 'reg_alpha': 0.022576010961294427, 'reg_lambda': 1.7226476161140238}. Best is trial 1 with value: 0.7788267730602504.
[I 2026-06-02 12:58:55,259] Trial 17 finished with value: 0.7781849676334943 and parameters: {'n_estimators': 1379, 'learning_rate': 0.023391802513028928, 'num_leaves': 57, 'max_depth': 13, 'subsample': 0.9890616586519715, 'colsample_bytree': 0.7739170435001403, 'reg_alpha': 2.0840019343919707, 'reg_lambda': 0.14203427735894814}. Best is trial 1 with value: 0.7788267730602504.
[I 2026-06-02 12:59:08,166] Trial 18 finished with value: 0.777787607371639 and parameters: {'n_estimators': 1039, 'learning_rate': 0.039384491805533946, 'num_leaves': 62, 'max_depth': 13, 'subsample': 0.9885242998432814, 'colsample_bytree': 0.7796546947053471, 'reg_alpha': 2.4559785560398653, 'reg_lambda': 0.021340321964503556}. Best is trial 1 with value: 0.7788267730602504.
[I 2026-06-02 12:59:49,454] Trial 19 finished with value: 0.7787580550686232 and parameters: {'n_estimators': 1414, 'learning_rate': 0.014386320900012125, 'num_leaves': 85, 'max_depth': 14, 'subsample': 0.9998845672938149, 'colsample_bytree': 0.9967755668540316, 'reg_alpha': 9.001308525198874, 'reg_lambda': 0.9320153253018721}. Best is trial 1 with value: 0.7788267730602504.
[I 2026-06-02 13:00:41,910] Trial 20 finished with value: 0.7785161208014286 and parameters: {'n_estimators': 1626, 'learning_rate': 0.013068164645668196, 'num_leaves': 123, 'max_depth': 15, 'subsample': 0.8787542140607459, 'colsample_bytree': 0.9813216101932155, 'reg_alpha': 9.284864613027448, 'reg_lambda': 3.64251161136439}. Best is trial 1 with value: 0.7788267730602504.
[I 2026-06-02 13:01:34,982] Trial 21 finished with value: 0.7789106063707395 and parameters: {'n_estimators': 1630, 'learning_rate': 0.014262655848419958, 'num_leaves': 121, 'max_depth': 15, 'subsample': 0.8856209682594977, 'colsample_bytree': 0.9986988736322205, 'reg_alpha': 9.623171875215423, 'reg_lambda': 4.030315500320551}. Best is trial 21 with value: 0.7789106063707395.
[I 2026-06-02 13:02:11,756] Trial 22 finished with value: 0.7786903107631805 and parameters: {'n_estimators': 1524, 'learning_rate': 0.016133787183644686, 'num_leaves': 82, 'max_depth': 14, 'subsample': 0.8996019123544994, 'colsample_bytree': 0.9373982260310427, 'reg_alpha': 9.68544484929029, 'reg_lambda': 0.9646425666036245}. Best is trial 21 with value: 0.7789106063707395.
[I 2026-06-02 13:02:59,426] Trial 23 finished with value: 0.7783470667668029 and parameters: {'n_estimators': 1282, 'learning_rate': 0.012090557379327063, 'num_leaves': 100, 'max_depth': 12, 'subsample': 0.9611254338677482, 'colsample_bytree': 0.997238032726882, 'reg_alpha': 3.888663717814024, 'reg_lambda': 8.802607544187499}. Best is trial 21 with value: 0.7789106063707395.
[I 2026-06-02 13:03:33,113] Trial 24 finished with value: 0.7771933841697387 and parameters: {'n_estimators': 1046, 'learning_rate': 0.017340481398111517, 'num_leaves': 148, 'max_depth': 14, 'subsample': 0.8313418786722557, 'colsample_bytree': 0.9174132048980445, 'reg_alpha': 0.5975324121560966, 'reg_lambda': 4.949237462739024}. Best is trial 21 with value: 0.7789106063707395.
[I 2026-06-02 13:04:10,847] Trial 25 finished with value: 0.7774461752162198 and parameters: {'n_estimators': 842, 'learning_rate': 0.013018030046304009, 'num_leaves': 87, 'max_depth': 11, 'subsample': 0.9191856868091501, 'colsample_bytree': 0.9718323467966782, 'reg_alpha': 3.43318566906148, 'reg_lambda': 0.7939308264523794}. Best is trial 21 with value: 0.7789106063707395.
[I 2026-06-02 13:05:07,979] Trial 26 finished with value: 0.7774109406161636 and parameters: {'n_estimators': 1740, 'learning_rate': 0.010261567489416973, 'num_leaves': 128, 'max_depth': 14, 'subsample': 0.7633639833371381, 'colsample_bytree': 0.8949967332488197, 'reg_alpha': 1.2425281467647828, 'reg_lambda': 2.510373456615464}. Best is trial 21 with value: 0.7789106063707395.
[I 2026-06-02 13:05:45,040] Trial 27 finished with value: 0.7781349922092621 and parameters: {'n_estimators': 1475, 'learning_rate': 0.017398994504417776, 'num_leaves': 112, 'max_depth': 12, 'subsample': 0.8571723918687713, 'colsample_bytree': 0.9618971029911002, 'reg_alpha': 9.718560520195979, 'reg_lambda': 0.3244318960707834}. Best is trial 21 with value: 0.7789106063707395.
[I 2026-06-02 13:06:18,319] Trial 28 finished with value: 0.77692194328788 and parameters: {'n_estimators': 1317, 'learning_rate': 0.014542779851131206, 'num_leaves': 80, 'max_depth': 15, 'subsample': 0.9582843374069862, 'colsample_bytree': 0.9956497823847421, 'reg_alpha': 0.6210383986028836, 'reg_lambda': 0.933323085362886}. Best is trial 21 with value: 0.7789106063707395.
[I 2026-06-02 13:06:38,841] Trial 29 finished with value: 0.7759119739183354 and parameters: {'n_estimators': 1805, 'learning_rate': 0.026016883015884902, 'num_leaves': 135, 'max_depth': 14, 'subsample': 0.8298785860418388, 'colsample_bytree': 0.8566744967439897, 'reg_alpha': 0.17418434933560348, 'reg_lambda': 0.07197949858813932}. Best is trial 21 with value: 0.7789106063707395.
[I 2026-06-02 13:07:04,368] Trial 30 finished with value: 0.777831087988026 and parameters: {'n_estimators': 1135, 'learning_rate': 0.02418830290650238, 'num_leaves': 94, 'max_depth': 11, 'subsample': 0.7004413199794034, 'colsample_bytree': 0.8881987386570638, 'reg_alpha': 4.710031557653359, 'reg_lambda': 2.4906022984117855}. Best is trial 21 with value: 0.7789106063707395.
[I 2026-06-02 13:07:39,041] Trial 31 finished with value: 0.7783980230104515 and parameters: {'n_estimators': 1556, 'learning_rate': 0.016559665018297216, 'num_leaves': 79, 'max_depth': 14, 'subsample': 0.8947302659437487, 'colsample_bytree': 0.9397630136124724, 'reg_alpha': 7.3808847320730155, 'reg_lambda': 0.7480727768538284}. Best is trial 21 with value: 0.7789106063707395.
[I 2026-06-02 13:08:18,244] Trial 32 finished with value: 0.7792032686181549 and parameters: {'n_estimators': 1525, 'learning_rate': 0.015241092364838726, 'num_leaves': 105, 'max_depth': 14, 'subsample': 0.8877765710406609, 'colsample_bytree': 0.9245458268254445, 'reg_alpha': 9.948336902609007, 'reg_lambda': 1.2003921886734954}. Best is trial 32 with value: 0.7792032686181549.
[I 2026-06-02 13:09:05,376] Trial 33 finished with value: 0.7773730274874464 and parameters: {'n_estimators': 1609, 'learning_rate': 0.012059988813674743, 'num_leaves': 107, 'max_depth': 15, 'subsample': 0.8358045482555859, 'colsample_bytree': 0.9603120660866389, 'reg_alpha': 2.0198339853201057, 'reg_lambda': 5.643627345011878}. Best is trial 32 with value: 0.7792032686181549.
[I 2026-06-02 13:09:34,756] Trial 34 finished with value: 0.7768045124541061 and parameters: {'n_estimators': 1190, 'learning_rate': 0.019748615954425147, 'num_leaves': 122, 'max_depth': 12, 'subsample': 0.8674598002439241, 'colsample_bytree': 0.915631954204409, 'reg_alpha': 3.253240421909641, 'reg_lambda': 0.2975117494096804}. Best is trial 32 with value: 0.7792032686181549.
[I 2026-06-02 13:10:09,039] Trial 35 finished with value: 0.7770394561538232 and parameters: {'n_estimators': 1916, 'learning_rate': 0.01481574573954713, 'num_leaves': 92, 'max_depth': 13, 'subsample': 0.9646877033150881, 'colsample_bytree': 0.9621031404554756, 'reg_alpha': 0.3471859672427549, 'reg_lambda': 2.2010852861510046}. Best is trial 32 with value: 0.7792032686181549.
[I 2026-06-02 13:10:36,369] Trial 36 finished with value: 0.7773961106265863 and parameters: {'n_estimators': 1731, 'learning_rate': 0.02002845038243914, 'num_leaves': 105, 'max_depth': 15, 'subsample': 0.9145569557159678, 'colsample_bytree': 0.9201078234015374, 'reg_alpha': 1.2921416190244022, 'reg_lambda': 3.5551062997347693}. Best is trial 32 with value: 0.7792032686181549.
[I 2026-06-02 13:11:01,348] Trial 37 finished with value: 0.7765048953053739 and parameters: {'n_estimators': 1416, 'learning_rate': 0.030788847935799186, 'num_leaves': 119, 'max_depth': 14, 'subsample': 0.761129056773304, 'colsample_bytree': 0.996471962187629, 'reg_alpha': 5.43615631975991, 'reg_lambda': 1.185092991114329}. Best is trial 32 with value: 0.7792032686181549.
[I 2026-06-02 13:11:37,409] Trial 38 finished with value: 0.776374439189749 and parameters: {'n_estimators': 1339, 'learning_rate': 0.012997741294181216, 'num_leaves': 130, 'max_depth': 10, 'subsample': 0.9259876368960237, 'colsample_bytree': 0.8769479322518046, 'reg_alpha': 0.7777478693227666, 'reg_lambda': 0.5006636732998396}. Best is trial 32 with value: 0.7792032686181549.
[I 2026-06-02 13:12:07,807] Trial 39 finished with value: 0.7772210718102122 and parameters: {'n_estimators': 1500, 'learning_rate': 0.01984978593932736, 'num_leaves': 143, 'max_depth': 12, 'subsample': 0.9950246311198836, 'colsample_bytree': 0.9483067067914472, 'reg_alpha': 2.825240832958163, 'reg_lambda': 0.07861684744708573}. Best is trial 32 with value: 0.7792032686181549.
[I 2026-06-02 13:12:34,212] Trial 40 finished with value: 0.7773980651321871 and parameters: {'n_estimators': 743, 'learning_rate': 0.02210083767514213, 'num_leaves': 96, 'max_depth': 13, 'subsample': 0.844724482993592, 'colsample_bytree': 0.9772709964041378, 'reg_alpha': 0.2911713112729588, 'reg_lambda': 7.644442787640556}. Best is trial 32 with value: 0.7792032686181549.
[I 2026-06-02 13:13:12,625] Trial 41 finished with value: 0.7786026290739627 and parameters: {'n_estimators': 1533, 'learning_rate': 0.015741033484542713, 'num_leaves': 80, 'max_depth': 14, 'subsample': 0.8937991431854614, 'colsample_bytree': 0.9293248663051707, 'reg_alpha': 8.939867691156495, 'reg_lambda': 1.0402008509767027}. Best is trial 32 with value: 0.7792032686181549.
[I 2026-06-02 13:13:42,886] Trial 42 finished with value: 0.7782181621291644 and parameters: {'n_estimators': 1670, 'learning_rate': 0.01778946058435353, 'num_leaves': 64, 'max_depth': 15, 'subsample': 0.943657969176132, 'colsample_bytree': 0.9519201144651209, 'reg_alpha': 5.603854533402652, 'reg_lambda': 0.5249115399071168}. Best is trial 32 with value: 0.7792032686181549.
[I 2026-06-02 13:14:30,291] Trial 43 finished with value: 0.7792227994076992 and parameters: {'n_estimators': 1800, 'learning_rate': 0.011835754679655579, 'num_leaves': 75, 'max_depth': 13, 'subsample': 0.9088890228641653, 'colsample_bytree': 0.9080242776378811, 'reg_alpha': 9.766642187212563, 'reg_lambda': 2.845608939607423}. Best is trial 43 with value: 0.7792227994076992.
[I 2026-06-02 13:15:12,579] Trial 44 finished with value: 0.7787898264844854 and parameters: {'n_estimators': 1773, 'learning_rate': 0.011117729882003238, 'num_leaves': 44, 'max_depth': 13, 'subsample': 0.8744083350603917, 'colsample_bytree': 0.9053320725925854, 'reg_alpha': 5.833746894047439, 'reg_lambda': 2.8589988873319245}. Best is trial 43 with value: 0.7792227994076992.
[I 2026-06-02 13:15:55,283] Trial 45 finished with value: 0.7786349283490016 and parameters: {'n_estimators': 1836, 'learning_rate': 0.011732691037408233, 'num_leaves': 51, 'max_depth': 11, 'subsample': 0.8729683402988679, 'colsample_bytree': 0.8217633580076832, 'reg_alpha': 4.303577285590043, 'reg_lambda': 2.860872248293578}. Best is trial 43 with value: 0.7792227994076992.
[I 2026-06-02 13:16:29,226] Trial 46 finished with value: 0.7759665502772847 and parameters: {'n_estimators': 1946, 'learning_rate': 0.010568818324365159, 'num_leaves': 48, 'max_depth': 4, 'subsample': 0.8187543837316174, 'colsample_bytree': 0.9057482530645224, 'reg_alpha': 2.0917099814235125, 'reg_lambda': 5.6607376719951565}. Best is trial 43 with value: 0.7792227994076992.
[I 2026-06-02 13:16:41,684] Trial 47 finished with value: 0.7770620613664113 and parameters: {'n_estimators': 1766, 'learning_rate': 0.0566915987728168, 'num_leaves': 112, 'max_depth': 11, 'subsample': 0.9100750442146875, 'colsample_bytree': 0.8413752235085884, 'reg_alpha': 5.6555645245295745, 'reg_lambda': 1.9037592690475624}. Best is trial 43 with value: 0.7792227994076992.
[I 2026-06-02 13:17:13,526] Trial 48 finished with value: 0.777134627736767 and parameters: {'n_estimators': 1891, 'learning_rate': 0.013234535991399909, 'num_leaves': 42, 'max_depth': 13, 'subsample': 0.8812892036182743, 'colsample_bytree': 0.873966411004946, 'reg_alpha': 0.8455778374430465, 'reg_lambda': 0.0012165606889204057}. Best is trial 43 with value: 0.7792227994076992.
[I 2026-06-02 13:17:40,623] Trial 49 finished with value: 0.7769119317965998 and parameters: {'n_estimators': 945, 'learning_rate': 0.011661183283462164, 'num_leaves': 32, 'max_depth': 12, 'subsample': 0.7850757620100602, 'colsample_bytree': 0.8004322783839017, 'reg_alpha': 6.3848096314818665, 'reg_lambda': 8.724295704698378}. Best is trial 43 with value: 0.7792227994076992.

In [48]:
lgb_study.best_params

{'n_estimators': 1800,
 'learning_rate': 0.011835754679655579,
 'num_leaves': 75,
 'max_depth': 13,
 'subsample': 0.9088890228641653,
 'colsample_bytree': 0.9080242776378811,
 'reg_alpha': 9.766642187212563,
 'reg_lambda': 2.845608939607423}

In [49]:
lgb_study.best_value

0.7792227994076992

## tunned lightgbm model

In [50]:
lgb_model = lgb.LGBMClassifier(
    **lgb_study.best_params,
    class_weight      = "balanced",
    random_state      = 42,
    n_jobs            = -1,
    verbose           = -1,
)

In [51]:
lgb_model.fit(
    X_train,
    y_train,
    eval_set=(X_val, y_val)
)

LGBMClassifier(class_weight='balanced', colsample_bytree=0.9080242776378811,
               learning_rate=0.011835754679655579, max_depth=13,
               n_estimators=1800, n_jobs=-1, num_leaves=75, random_state=42,
               reg_alpha=9.766642187212563, reg_lambda=2.845608939607423,
               subsample=0.9088890228641653, verbose=-1)

In [52]:
lgb_pred = lgb_model.predict_proba(X_val)[:,1]
lgb_auc = roc_auc_score(y_val, lgb_pred)
print(lgb_auc)

0.7791596239374294

### hyperparameter tuning with optuna for catboost

In [ ]:
# =========================================
# OPTUNA OBJECTIVE FUNCTION FOR CATBOOST
# =========================================

def objective(trial):

    params = {
        'loss_function': 'Logloss',
        'eval_metric': 'AUC',

        'iterations': trial.suggest_int('iterations',300,2000),

        'learning_rate': trial.suggest_float('learning_rate',0.01,0.1,log=True),

        'depth': trial.suggest_int('depth',4,10),

        'l2_leaf_reg': trial.suggest_float('l2_leaf_reg',1e-3,10.0,log=True),

        'subsample': trial.suggest_float('subsample',0.6,1.0),

        'random_strength': trial.suggest_float('random_strength',1e-3,10.0,log=True),

        'bagging_temperature': trial.suggest_float('bagging_temperature',0,10),

        'scale_pos_weight': trial.suggest_float('scale_pos_weight',1,10),

        'random_state': 42,

        'verbose': 0
    }

    # =====================================
    # MODEL
    # =====================================

    cat_model = CatBoostClassifier(**params)

    # =====================================
    # TRAIN
    # =====================================

    cat_model.fit(X_train,y_train,

        eval_set=(X_val, y_val),

        early_stopping_rounds=50,

        verbose=False
    )

    # =====================================
    # PREDICTION
    # =====================================

    pred_prob = cat_model.predict_proba(X_val)[:,1]

    # =====================================
    # ROC-AUC
    # =====================================

    auc = roc_auc_score(y_val,pred_prob)

    return auc

In [54]:
cat_study = optuna.create_study(direction='maximize')

cat_study.optimize(objective,n_trials=76)

[I 2026-06-02 13:18:41,352] A new study created in memory with name: no-name-ce8ffeb1-c8c2-44a3-8f09-62acb342163e
[I 2026-06-02 13:19:53,648] Trial 0 finished with value: 0.7738843526882531 and parameters: {'iterations': 1618, 'learning_rate': 0.01617997822308227, 'depth': 9, 'l2_leaf_reg': 0.08169360158950896, 'subsample': 0.6542666857802705, 'random_strength': 0.27496508098547967, 'bagging_temperature': 7.285412984395769, 'scale_pos_weight': 6.298208684047573}. Best is trial 0 with value: 0.7738843526882531.
[I 2026-06-02 13:20:15,327] Trial 1 finished with value: 0.7782347076610663 and parameters: {'iterations': 1919, 'learning_rate': 0.0940841727586411, 'depth': 4, 'l2_leaf_reg': 0.015119143828827704, 'subsample': 0.9353860550292014, 'random_strength': 0.3594296134464122, 'bagging_temperature': 4.514491348171898, 'scale_pos_weight': 6.9732881101265125}. Best is trial 1 with value: 0.7782347076610663.
[I 2026-06-02 13:21:16,306] Trial 2 finished with value: 0.7739466900037489 and parameters: {'iterations': 887, 'learning_rate': 0.013410546243929723, 'depth': 8, 'l2_leaf_reg': 0.0015853746730750268, 'subsample': 0.6440740315373839, 'random_strength': 0.0021517323090041803, 'bagging_temperature': 0.9212265124063435, 'scale_pos_weight': 7.654072825768818}. Best is trial 1 with value: 0.7782347076610663.
[I 2026-06-02 13:22:27,472] Trial 3 finished with value: 0.7717517195815174 and parameters: {'iterations': 875, 'learning_rate': 0.05941667671839576, 'depth': 10, 'l2_leaf_reg': 0.8078250914757986, 'subsample': 0.7219708083173784, 'random_strength': 1.070605782839222, 'bagging_temperature': 9.791091537014541, 'scale_pos_weight': 3.0823149933406904}. Best is trial 1 with value: 0.7782347076610663.
[I 2026-06-02 13:22:42,529] Trial 4 finished with value: 0.7722775315207718 and parameters: {'iterations': 366, 'learning_rate': 0.09771466473897275, 'depth': 7, 'l2_leaf_reg': 0.007723452206641585, 'subsample': 0.9649290393226172, 'random_strength': 0.017023216755582122, 'bagging_temperature': 6.0478987852670665, 'scale_pos_weight': 3.888866749536999}. Best is trial 1 with value: 0.7782347076610663.
[I 2026-06-02 13:23:47,064] Trial 5 finished with value: 0.7782770255606177 and parameters: {'iterations': 1758, 'learning_rate': 0.022436696828350804, 'depth': 4, 'l2_leaf_reg': 0.06340701322871854, 'subsample': 0.7253013663909644, 'random_strength': 0.3567634824111645, 'bagging_temperature': 2.1852643579811613, 'scale_pos_weight': 7.833664831001283}. Best is trial 5 with value: 0.7782770255606177.
[I 2026-06-02 13:24:20,870] Trial 6 finished with value: 0.7789816426628056 and parameters: {'iterations': 1420, 'learning_rate': 0.07418259386887552, 'depth': 4, 'l2_leaf_reg': 0.03376894387639388, 'subsample': 0.9101732031049321, 'random_strength': 0.0012464897914877067, 'bagging_temperature': 8.094481950397581, 'scale_pos_weight': 4.162122144526051}. Best is trial 6 with value: 0.7789816426628056.
[I 2026-06-02 13:24:45,254] Trial 7 finished with value: 0.7776377238983357 and parameters: {'iterations': 1434, 'learning_rate': 0.08369834413232023, 'depth': 5, 'l2_leaf_reg': 0.036061794313721085, 'subsample': 0.9667916265101872, 'random_strength': 0.06357793251692466, 'bagging_temperature': 2.548684649596251, 'scale_pos_weight': 7.219695212654381}. Best is trial 6 with value: 0.7789816426628056.
[I 2026-06-02 13:26:44,920] Trial 8 finished with value: 0.779728937892767 and parameters: {'iterations': 1203, 'learning_rate': 0.020630591389218255, 'depth': 9, 'l2_leaf_reg': 2.915628016531957, 'subsample': 0.7828180949120711, 'random_strength': 0.3402566018032481, 'bagging_temperature': 6.505074230524791, 'scale_pos_weight': 3.6646429010527357}. Best is trial 8 with value: 0.779728937892767.
[I 2026-06-02 13:27:06,537] Trial 9 finished with value: 0.7711204570718346 and parameters: {'iterations': 1688, 'learning_rate': 0.09732083714695137, 'depth': 8, 'l2_leaf_reg': 0.10943788149385615, 'subsample': 0.6372421889812455, 'random_strength': 5.374608556537391, 'bagging_temperature': 4.826939972997178, 'scale_pos_weight': 4.400383250567853}. Best is trial 8 with value: 0.779728937892767.
[I 2026-06-02 13:27:59,796] Trial 10 finished with value: 0.7789017254967503 and parameters: {'iterations': 1017, 'learning_rate': 0.03758431581769304, 'depth': 6, 'l2_leaf_reg': 5.252313907883538, 'subsample': 0.84185293774714, 'random_strength': 7.1767816594738, 'bagging_temperature': 9.91445884845873, 'scale_pos_weight': 1.4643755697440235}. Best is trial 8 with value: 0.779728937892767.
[I 2026-06-02 13:29:48,500] Trial 11 finished with value: 0.7749063130209911 and parameters: {'iterations': 1276, 'learning_rate': 0.03427553889225095, 'depth': 10, 'l2_leaf_reg': 0.7868379124326054, 'subsample': 0.856216317665977, 'random_strength': 0.002078170700252361, 'bagging_temperature': 7.689209230544132, 'scale_pos_weight': 2.054996745031544}. Best is trial 8 with value: 0.779728937892767.
[I 2026-06-02 13:31:01,427] Trial 12 finished with value: 0.7797906546170684 and parameters: {'iterations': 1327, 'learning_rate': 0.023037962033944318, 'depth': 7, 'l2_leaf_reg': 8.036705433846366, 'subsample': 0.8856206585291362, 'random_strength': 0.018433631663158898, 'bagging_temperature': 7.569160872203198, 'scale_pos_weight': 9.875688803253242}. Best is trial 12 with value: 0.7797906546170684.
[I 2026-06-02 13:31:40,710] Trial 13 finished with value: 0.7771217914855673 and parameters: {'iterations': 648, 'learning_rate': 0.02400506772280723, 'depth': 7, 'l2_leaf_reg': 7.141398202985158, 'subsample': 0.7838177308719539, 'random_strength': 0.016672520689438173, 'bagging_temperature': 6.291916775690232, 'scale_pos_weight': 9.342620116597814}. Best is trial 12 with value: 0.7797906546170684.
[I 2026-06-02 13:33:08,122] Trial 14 finished with value: 0.7774147426288834 and parameters: {'iterations': 1184, 'learning_rate': 0.010709195825417754, 'depth': 8, 'l2_leaf_reg': 1.5411591637666606, 'subsample': 0.7918762632815708, 'random_strength': 0.030479768706015542, 'bagging_temperature': 8.70465255842159, 'scale_pos_weight': 5.26111621590907}. Best is trial 12 with value: 0.7797906546170684.
[I 2026-06-02 13:34:22,668] Trial 15 finished with value: 0.7794648834727684 and parameters: {'iterations': 1383, 'learning_rate': 0.023035296538258813, 'depth': 6, 'l2_leaf_reg': 2.719023638622935, 'subsample': 0.8615394066109964, 'random_strength': 0.0062912039742265705, 'bagging_temperature': 6.087941972829177, 'scale_pos_weight': 9.127860715696752}. Best is trial 12 with value: 0.7797906546170684.
[I 2026-06-02 13:35:09,401] Trial 16 finished with value: 0.7741621100471539 and parameters: {'iterations': 1057, 'learning_rate': 0.04607547995277113, 'depth': 9, 'l2_leaf_reg': 0.30573747721847844, 'subsample': 0.7288602669655939, 'random_strength': 0.10628087426643841, 'bagging_temperature': 3.8169310031706107, 'scale_pos_weight': 2.7497250601598053}. Best is trial 12 with value: 0.7797906546170684.
[I 2026-06-02 13:35:50,172] Trial 17 finished with value: 0.7698311966984834 and parameters: {'iterations': 644, 'learning_rate': 0.01745585441811706, 'depth': 7, 'l2_leaf_reg': 0.40455848566953595, 'subsample': 0.8981722926813042, 'random_strength': 1.758729314463547, 'bagging_temperature': 6.81126917271767, 'scale_pos_weight': 5.704576389738593}. Best is trial 12 with value: 0.7797906546170684.
[I 2026-06-02 13:37:16,901] Trial 18 finished with value: 0.7787174134786202 and parameters: {'iterations': 1580, 'learning_rate': 0.027484207980114733, 'depth': 9, 'l2_leaf_reg': 9.356562585779903, 'subsample': 0.8226905484174883, 'random_strength': 0.10262148324916298, 'bagging_temperature': 8.71971357695667, 'scale_pos_weight': 9.90005946491875}. Best is trial 12 with value: 0.7797906546170684.
[I 2026-06-02 13:38:58,974] Trial 19 finished with value: 0.7798137520226726 and parameters: {'iterations': 1969, 'learning_rate': 0.017348811644541787, 'depth': 6, 'l2_leaf_reg': 2.520982125517304, 'subsample': 0.7654690492544334, 'random_strength': 0.0070062384564947115, 'bagging_temperature': 5.46059989123065, 'scale_pos_weight': 8.391327810823935}. Best is trial 19 with value: 0.7798137520226726.
[I 2026-06-02 13:40:34,543] Trial 20 finished with value: 0.777064843326938 and parameters: {'iterations': 1927, 'learning_rate': 0.010005775971993853, 'depth': 6, 'l2_leaf_reg': 2.0452981028374566, 'subsample': 0.6844502705358981, 'random_strength': 0.006455833158743765, 'bagging_temperature': 3.3001334496632575, 'scale_pos_weight': 8.372557383720437}. Best is trial 19 with value: 0.7798137520226726.
[I 2026-06-02 13:41:31,421] Trial 21 finished with value: 0.7765550347939446 and parameters: {'iterations': 1228, 'learning_rate': 0.017825113982301608, 'depth': 5, 'l2_leaf_reg': 3.504085662069845, 'subsample': 0.7636529591533626, 'random_strength': 0.005771887026428614, 'bagging_temperature': 5.485829573265439, 'scale_pos_weight': 8.839742035284914}. Best is trial 19 with value: 0.7798137520226726.
[I 2026-06-02 13:43:25,504] Trial 22 finished with value: 0.779396618441381 and parameters: {'iterations': 1987, 'learning_rate': 0.013978118307752226, 'depth': 7, 'l2_leaf_reg': 0.8699976761106181, 'subsample': 0.7547853520426151, 'random_strength': 0.03776598235761681, 'bagging_temperature': 5.241344467333869, 'scale_pos_weight': 9.540582752754885}. Best is trial 19 with value: 0.7798137520226726.
[I 2026-06-02 13:44:39,848] Trial 23 finished with value: 0.7794252334020298 and parameters: {'iterations': 1475, 'learning_rate': 0.01915591833665788, 'depth': 6, 'l2_leaf_reg': 9.144536246900602, 'subsample': 0.8152804822452887, 'random_strength': 0.01353639955349439, 'bagging_temperature': 6.911590247623348, 'scale_pos_weight': 9.996473610793817}. Best is trial 19 with value: 0.7798137520226726.
[I 2026-06-02 13:45:38,250] Trial 24 finished with value: 0.7786691107973203 and parameters: {'iterations': 1806, 'learning_rate': 0.029123554715250213, 'depth': 5, 'l2_leaf_reg': 0.2967258784558282, 'subsample': 0.878898096492523, 'random_strength': 0.9190194342672393, 'bagging_temperature': 8.300678901090222, 'scale_pos_weight': 8.11872263960793}. Best is trial 19 with value: 0.7798137520226726.
[I 2026-06-02 13:46:30,421] Trial 25 finished with value: 0.7749717746921556 and parameters: {'iterations': 771, 'learning_rate': 0.013035168598958462, 'depth': 8, 'l2_leaf_reg': 1.591847646611981, 'subsample': 0.7012008899479503, 'random_strength': 0.13516483380146216, 'bagging_temperature': 4.351476234386225, 'scale_pos_weight': 8.610208490658215}. Best is trial 19 with value: 0.7798137520226726.
[I 2026-06-02 13:46:49,363] Trial 26 finished with value: 0.7705587364420886 and parameters: {'iterations': 345, 'learning_rate': 0.02052941652972258, 'depth': 7, 'l2_leaf_reg': 4.151251444840406, 'subsample': 0.6067403173140067, 'random_strength': 0.044965223426223465, 'bagging_temperature': 0.011278163571553534, 'scale_pos_weight': 4.947431614312447}. Best is trial 19 with value: 0.7798137520226726.
[I 2026-06-02 13:47:37,831] Trial 27 finished with value: 0.7746716760502552 and parameters: {'iterations': 1045, 'learning_rate': 0.03771433946262106, 'depth': 9, 'l2_leaf_reg': 1.361572038354123, 'subsample': 0.9953858565743128, 'random_strength': 0.003907265572897339, 'bagging_temperature': 5.817308610248627, 'scale_pos_weight': 6.344748531217561}. Best is trial 19 with value: 0.7798137520226726.
[I 2026-06-02 13:48:42,558] Trial 28 finished with value: 0.7769831678191652 and parameters: {'iterations': 1312, 'learning_rate': 0.014885822085807864, 'depth': 6, 'l2_leaf_reg': 0.16600044644463258, 'subsample': 0.7634371129267857, 'random_strength': 0.012579453495274168, 'bagging_temperature': 6.628656066717893, 'scale_pos_weight': 3.3155503933804265}. Best is trial 19 with value: 0.7798137520226726.
[I 2026-06-02 13:50:00,597] Trial 29 finished with value: 0.777468131304685 and parameters: {'iterations': 1588, 'learning_rate': 0.026429040754462584, 'depth': 9, 'l2_leaf_reg': 3.4073397596237376, 'subsample': 0.834760536950987, 'random_strength': 0.17685428025759084, 'bagging_temperature': 7.461750410541794, 'scale_pos_weight': 6.973356507687349}. Best is trial 19 with value: 0.7798137520226726.
[I 2026-06-02 13:51:11,008] Trial 30 finished with value: 0.7778881930777617 and parameters: {'iterations': 1531, 'learning_rate': 0.016419228647298428, 'depth': 5, 'l2_leaf_reg': 5.846122903706642, 'subsample': 0.8026592385372983, 'random_strength': 0.2618079305948665, 'bagging_temperature': 9.163857949153687, 'scale_pos_weight': 5.711640416736828}. Best is trial 19 with value: 0.7798137520226726.
[I 2026-06-02 13:52:23,362] Trial 31 finished with value: 0.7792154593118479 and parameters: {'iterations': 1329, 'learning_rate': 0.022463450479288306, 'depth': 6, 'l2_leaf_reg': 2.467578040598555, 'subsample': 0.8673770232414516, 'random_strength': 0.008031363714163272, 'bagging_temperature': 7.344979166043381, 'scale_pos_weight': 8.870653365913721}. Best is trial 19 with value: 0.7798137520226726.
[I 2026-06-02 13:53:20,911] Trial 32 finished with value: 0.778443500931832 and parameters: {'iterations': 1123, 'learning_rate': 0.020150068912748943, 'depth': 6, 'l2_leaf_reg': 3.2470138353322486, 'subsample': 0.91303318131812, 'random_strength': 0.002869472387889929, 'bagging_temperature': 5.646662095586111, 'scale_pos_weight': 6.291719733966693}. Best is trial 19 with value: 0.7798137520226726.
[I 2026-06-02 13:54:24,325] Trial 33 finished with value: 0.7782588179856316 and parameters: {'iterations': 1801, 'learning_rate': 0.024857985853071956, 'depth': 7, 'l2_leaf_reg': 0.5033163261869994, 'subsample': 0.9357882765665868, 'random_strength': 0.02567881091151187, 'bagging_temperature': 4.273846037696636, 'scale_pos_weight': 8.876105441900497}. Best is trial 19 with value: 0.7798137520226726.
[I 2026-06-02 13:54:52,313] Trial 34 finished with value: 0.7708049328154751 and parameters: {'iterations': 932, 'learning_rate': 0.030445117709949805, 'depth': 8, 'l2_leaf_reg': 0.003218111533839115, 'subsample': 0.8918717510341414, 'random_strength': 0.0011204594291579263, 'bagging_temperature': 6.384228688872979, 'scale_pos_weight': 9.467219758219507}. Best is trial 19 with value: 0.7798137520226726.
[I 2026-06-02 13:59:27,193] Trial 35 finished with value: 0.7755914563994917 and parameters: {'iterations': 1370, 'learning_rate': 0.012400812189968797, 'depth': 10, 'l2_leaf_reg': 1.2192905797192006, 'subsample': 0.8542003546543169, 'random_strength': 0.844096056085814, 'bagging_temperature': 4.895484903011085, 'scale_pos_weight': 7.619278409923428}. Best is trial 19 with value: 0.7798137520226726.
[I 2026-06-02 14:01:07,536] Trial 36 finished with value: 0.7788819593105459 and parameters: {'iterations': 1680, 'learning_rate': 0.015611036364623253, 'depth': 8, 'l2_leaf_reg': 2.23514422472619, 'subsample': 0.7774328630901166, 'random_strength': 0.004685970691090507, 'bagging_temperature': 7.0801307874890655, 'scale_pos_weight': 8.133314455836267}. Best is trial 19 with value: 0.7798137520226726.
[I 2026-06-02 14:01:49,223] Trial 37 finished with value: 0.7795280482431901 and parameters: {'iterations': 1167, 'learning_rate': 0.04408101827588805, 'depth': 6, 'l2_leaf_reg': 0.6865789620193907, 'subsample': 0.7417159605437436, 'random_strength': 0.00862572492667486, 'bagging_temperature': 5.943930753861366, 'scale_pos_weight': 9.109858194919562}. Best is trial 19 with value: 0.7798137520226726.
[I 2026-06-02 14:02:22,256] Trial 38 finished with value: 0.7799471077971541 and parameters: {'iterations': 789, 'learning_rate': 0.05731153808323727, 'depth': 5, 'l2_leaf_reg': 0.5555024780076482, 'subsample': 0.7416085513582622, 'random_strength': 0.06574222799599315, 'bagging_temperature': 7.8442809168745224, 'scale_pos_weight': 6.333702496791701}. Best is trial 38 with value: 0.7799471077971541.
[I 2026-06-02 14:02:51,724] Trial 39 finished with value: 0.7786701130164332 and parameters: {'iterations': 786, 'learning_rate': 0.05807641302384688, 'depth': 4, 'l2_leaf_reg': 0.23310757492997616, 'subsample': 0.6926143024744681, 'random_strength': 0.529927303573309, 'bagging_temperature': 9.319060655897829, 'scale_pos_weight': 6.4936480175513145}. Best is trial 38 with value: 0.7799471077971541.
[I 2026-06-02 14:03:09,503] Trial 40 finished with value: 0.77807858974289 and parameters: {'iterations': 436, 'learning_rate': 0.06366319469821696, 'depth': 5, 'l2_leaf_reg': 5.004058909152216, 'subsample': 0.6677863682712704, 'random_strength': 0.06736988146386935, 'bagging_temperature': 7.8747820460147, 'scale_pos_weight': 3.7003341143974255}. Best is trial 38 with value: 0.7799471077971541.
[I 2026-06-02 14:03:49,556] Trial 41 finished with value: 0.7805491704211542 and parameters: {'iterations': 1130, 'learning_rate': 0.04699851593707351, 'depth': 5, 'l2_leaf_reg': 0.6303229357312693, 'subsample': 0.7443620284381038, 'random_strength': 0.00960995161413207, 'bagging_temperature': 8.40866810492293, 'scale_pos_weight': 7.445194054408112}. Best is trial 41 with value: 0.7805491704211542.
[I 2026-06-02 14:04:24,140] Trial 42 finished with value: 0.7793177819599917 and parameters: {'iterations': 918, 'learning_rate': 0.051229348573005554, 'depth': 4, 'l2_leaf_reg': 1.0431541297376774, 'subsample': 0.7109673757532323, 'random_strength': 0.02070863304104547, 'bagging_temperature': 7.864379493778896, 'scale_pos_weight': 7.449557856718451}. Best is trial 41 with value: 0.7805491704211542.
[I 2026-06-02 14:04:47,657] Trial 43 finished with value: 0.778085961938286 and parameters: {'iterations': 562, 'learning_rate': 0.07421010845881455, 'depth': 5, 'l2_leaf_reg': 0.07241918893070187, 'subsample': 0.747606746762659, 'random_strength': 0.054403768303679254, 'bagging_temperature': 8.478128056992478, 'scale_pos_weight': 6.8683409857182305}. Best is trial 41 with value: 0.7805491704211542.
[I 2026-06-02 14:05:21,471] Trial 44 finished with value: 0.7782318615014505 and parameters: {'iterations': 815, 'learning_rate': 0.03280038412279327, 'depth': 5, 'l2_leaf_reg': 0.5293280071997588, 'subsample': 0.7313826059106947, 'random_strength': 0.20523078398300867, 'bagging_temperature': 9.06030804029469, 'scale_pos_weight': 4.90952022353141}. Best is trial 41 with value: 0.7805491704211542.
[I 2026-06-02 14:06:02,946] Trial 45 finished with value: 0.7786300920176243 and parameters: {'iterations': 985, 'learning_rate': 0.04199727709976683, 'depth': 5, 'l2_leaf_reg': 0.13202774047800417, 'subsample': 0.8010504158967809, 'random_strength': 0.01167940173610265, 'bagging_temperature': 7.208623765067411, 'scale_pos_weight': 7.985775646852505}. Best is trial 41 with value: 0.7805491704211542.
[I 2026-06-02 14:06:45,338] Trial 46 finished with value: 0.7786588995755407 and parameters: {'iterations': 1120, 'learning_rate': 0.05431133527661707, 'depth': 4, 'l2_leaf_reg': 0.028411566737542148, 'subsample': 0.7703077980439095, 'random_strength': 0.0019388697319607177, 'bagging_temperature': 7.962938660860486, 'scale_pos_weight': 1.0802803733314095}. Best is trial 41 with value: 0.7805491704211542.
[I 2026-06-02 14:07:22,276] Trial 47 finished with value: 0.7808945008879269 and parameters: {'iterations': 707, 'learning_rate': 0.06683124761778761, 'depth': 7, 'l2_leaf_reg': 5.862282569699471, 'subsample': 0.7154694532202521, 'random_strength': 2.0905950234592137, 'bagging_temperature': 6.487064325888548, 'scale_pos_weight': 2.3463385157075636}. Best is trial 47 with value: 0.7808945008879269.
[I 2026-06-02 14:07:56,176] Trial 48 finished with value: 0.7794615736530648 and parameters: {'iterations': 632, 'learning_rate': 0.06775778436772069, 'depth': 7, 'l2_leaf_reg': 7.146469389023223, 'subsample': 0.7138759664586983, 'random_strength': 3.32106840884624, 'bagging_temperature': 9.664693823527852, 'scale_pos_weight': 7.343245274885533}. Best is trial 47 with value: 0.7808945008879269.

In [55]:
cat_study.best_params

{'iterations': 923,
 'learning_rate': 0.06246840050225421,
 'depth': 5,
 'l2_leaf_reg': 0.40763839648570827,
 'subsample': 0.6201912349614332,
 'random_strength': 1.0425028928591424,
 'bagging_temperature': 3.643906711290002,
 'scale_pos_weight': 3.5294845828216053}

In [56]:
cat_study.best_value

0.7812454701746904

In [57]:
# =========================================
# FINAL TUNED CATBOOST MODEL
# =========================================
cat_model = CatBoostClassifier(
    **cat_study.best_params,
    loss_function='Logloss',
    eval_metric='AUC',
    random_state=42,
    verbose=100
)

# =========================================
# TRAIN MODEL
# =========================================

cat_model.fit(

    X_train,
    y_train,

    eval_set=(X_val, y_val),

    early_stopping_rounds=50,

    verbose=False
)

# =========================================
# PREDICTIONS
# =========================================

cat_pred = cat_model.predict_proba(X_val)[:,1]

# =========================================
# ROC-AUC SCORE
# =========================================

cat_auc = roc_auc_score(y_val,cat_pred)

print("CatBoost ROC-AUC :", cat_auc)

CatBoost ROC-AUC : 0.7812454701746904

In [58]:
feature_imp = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': cat_model.feature_importances_
}).sort_values(
    by='Importance',
    ascending=False
)

feature_imp.tail(50)

                         Feature  Importance
73             AVG_BUREAU_STATUS    0.176143
118             DPD_OVER_30_MEAN    0.175565
95          AVG_SEVERE_DPD_RATIO    0.175050
4                   CNT_CHILDREN    0.172988
128               AVG_CC_BALANCE    0.161320
101      OVERDUE_PER_ACTIVE_LOAN    0.159812
141               AVG_RECEIVABLE    0.154330
13             NAME_HOUSING_TYPE    0.146403
135                   AVG_CC_DPD    0.142030
9                NAME_TYPE_SUITE    0.140530
139         MAX_DRAWINGS_CURRENT    0.130814
0             NAME_CONTRACT_TYPE    0.127652
55       TOTAL_PREV_APPLICATIONS    0.122181
26          REGION_RATING_CLIENT    0.109566
59               AVG_PREV_CREDIT    0.100818
151                  AVG_POS_DPD    0.096663
83                 TOTAL_OVERDUE    0.095989
136                   MAX_CC_DPD    0.092099
84                   MAX_OVERDUE    0.088258
25               CNT_FAM_MEMBERS    0.086478
87        MAX_CREDIT_DAY_OVERDUE    0.085782
131                 MAX_CC_LIMIT    0.077206
123              DPD_OVER_60_STD    0.064221
44    AMT_REQ_CREDIT_BUREAU_WEEK    0.063026
86        AVG_CREDIT_DAY_OVERDUE    0.061801
99       OVERDUE_TO_CREDIT_RATIO    0.054202
72             MAX_BUREAU_STATUS    0.053090
30    REG_REGION_NOT_LIVE_REGION    0.046419
85                   HAS_OVERDUE    0.044917
19                FLAG_EMP_PHONE    0.043773
120              DPD_OVER_30_STD    0.039159
43     AMT_REQ_CREDIT_BUREAU_DAY    0.036005
34        REG_CITY_NOT_WORK_CITY    0.031798
50         IS_HIGH_RISK_BUILDING    0.028938
52         IS_LOW_RISK_HOUSETYPE    0.024838
42    AMT_REQ_CREDIT_BUREAU_HOUR    0.021652
124             DPD_OVER_90_MEAN    0.020336
126              DPD_OVER_90_STD    0.019363
35       LIVE_CITY_NOT_WORK_CITY    0.015475
23                    FLAG_EMAIL    0.013910
21              FLAG_CONT_MOBILE    0.000000
3                FLAG_OWN_REALTY    0.000000
32   LIVE_REGION_NOT_WORK_REGION    0.000000
31    REG_REGION_NOT_WORK_REGION    0.000000
49             HAS_BUILDING_INFO    0.000000
93               HAS_DPD_HISTORY    0.000000
121             DPD_OVER_60_MEAN    0.000000
122              DPD_OVER_60_MAX    0.000000
119              DPD_OVER_30_MAX    0.000000
125              DPD_OVER_90_MAX    0.000000

### checking if dropping 0 importance in both models improves performance

In [59]:
col_to_drop = feature_imp[feature_imp['Importance'] == 0]['Feature'].tolist()
X_train_reduced = X_train.drop(columns=col_to_drop)
X_val_reduced = X_val.drop(columns=col_to_drop)

In [60]:
cat_model.fit(

    X_train_reduced,
    y_train,

    eval_set=(X_val_reduced, y_val),

    early_stopping_rounds=50,

    verbose=False
)
cat_pred = cat_model.predict_proba(X_val_reduced)[:,1]
cat_auc = roc_auc_score(y_val,cat_pred)

print("CatBoost ROC-AUC :", cat_auc)

CatBoost ROC-AUC : 0.7809253806497739

### instead of helping it actually made it drop the roc_auc, so we will keep all features for the final model

### ensemble on two models
ensemble_pred = 0.5 * cat_pred + 0.5 * lgb_pred

In [61]:
blend_pred = (
    0.5 * lgb_pred
    +
    0.5 * cat_pred
)

In [62]:
blend_auc = roc_auc_score(y_val,blend_pred)

print("Blended ROC-AUC :", blend_auc)

Blended ROC-AUC : 0.7817484272382327

### FINAL xgboost model

In [63]:
# =========================================
# XGBOOST MODEL
# =========================================
xgb_model = XGBClassifier(
    objective='binary:logistic',
    eval_metric='auc',
    n_estimators=1000,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.1,
    reg_lambda=0.1,
    scale_pos_weight=(
        y_train.value_counts()[0]
        /
        y_train.value_counts()[1]
    ),
    random_state=42,
    n_jobs=-1
)

# =========================================
# TRAIN XGBOOST
# =========================================

xgb_model.fit(

    X_train,
    y_train,

    eval_set=[(X_val, y_val)],

    verbose=False
)

# =========================================
# XGBOOST PREDICTIONS
# =========================================

xgb_pred = xgb_model.predict_proba(X_val)[:,1]

# =========================================
# XGBOOST ROC-AUC
# =========================================

xgb_auc = roc_auc_score(y_val,xgb_pred)

print("XGBoost ROC-AUC :", xgb_auc)

XGBoost ROC-AUC : 0.7698377343057212

In [64]:
# =========================================
# TRIPLE ENSEMBLE
# =========================================

ensemble_pred_prob = (
    0.5 * cat_pred
    +
    0.3 * lgb_pred
    +
    0.2 * xgb_pred
)

# =========================================
# ENSEMBLE ROC-AUC
# =========================================

ensemble_auc = roc_auc_score(y_val,ensemble_pred_prob)

print("Triple Ensemble ROC-AUC :", ensemble_auc)

Triple Ensemble ROC-AUC : 0.7819578161338802

In [65]:
ensemble_pred = (ensemble_pred_prob >= 0.5).astype(int)

In [66]:
print(classification_report(y_val,ensemble_pred))

              precision    recall  f1-score   support

           0       0.95      0.90      0.92     56505
           1       0.27      0.44      0.34      4962

    accuracy                           0.86     61467
   macro avg       0.61      0.67      0.63     61467
weighted avg       0.89      0.86      0.87     61467

In [67]:
print(confusion_matrix(y_val,ensemble_pred))

[[50641  5864]
 [ 2782  2180]]

### threshold tuning

In [68]:
thresholds = np.arange(0.10, 0.91, 0.01)

results = []

for threshold in thresholds:

    pred = (ensemble_pred_prob >= threshold).astype(int)
    f1 = f1_score(y_val,pred)
    results.append([threshold, f1])

results = pd.DataFrame(
    results,
    columns=['Threshold', 'F1']
)

results.sort_values(by='F1',ascending=False).head(10)

    Threshold        F1
41       0.51  0.335320
40       0.50  0.335230
43       0.53  0.335031
39       0.49  0.334699
42       0.52  0.334455
38       0.48  0.333669
37       0.47  0.332156
44       0.54  0.330959
35       0.45  0.330336
36       0.46  0.330299

In [69]:
best_threshold = 0.55

final_pred = (ensemble_pred_prob >= best_threshold).astype(int)

print(classification_report(y_val,final_pred))
print(confusion_matrix(y_val,final_pred))

              precision    recall  f1-score   support

           0       0.94      0.93      0.93     56505
           1       0.30      0.36      0.33      4962

    accuracy                           0.88     61467
   macro avg       0.62      0.64      0.63     61467
weighted avg       0.89      0.88      0.89     61467

[[52300  4205]
 [ 3161  1801]]

### final model comparison

In [70]:
comparison = pd.DataFrame({

    'Model':[
        'LightGBM',
        'CatBoost',
        'XGBoost',
        'Triple Ensemble'
    ],

    'ROC_AUC':[
        lgb_auc,
        cat_auc,
        xgb_auc,
        ensemble_auc
    ]
})

comparison.sort_values(
    by='ROC_AUC',
    ascending=False
)

             Model   ROC_AUC
3  Triple Ensemble  0.781958
1         CatBoost  0.780925
0         LightGBM  0.779160
2          XGBoost  0.769838

# Retrain models on full training data

In [71]:
lgb_final = lgb.LGBMClassifier(
    **lgb_study.best_params,
    class_weight      = "balanced",
    random_state      = 42,
    n_jobs            = -1,
    verbose           = -1,
)

cat_final = CatBoostClassifier(
    **cat_study.best_params,
    loss_function='Logloss',
    eval_metric='AUC',
    random_state=42,
    verbose=100
)

xgb_final = XGBClassifier(
    objective='binary:logistic',
    eval_metric='auc',
    n_estimators=1000,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.1,
    reg_lambda=0.1,
    scale_pos_weight=(
        y.value_counts()[0]
        /
        y.value_counts()[1]
    ),
    random_state=42,
    n_jobs=-1
)

In [72]:
cat_final.fit(X, y,verbose=False)
lgb_final.fit(X, y)
xgb_final.fit(X, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='auc', feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=1000,
              n_jobs=-1, num_parallel_tree=None, ...)

In [73]:
ensemble_info = {

    'cat_weight': 0.5,

    'lgb_weight': 0.3,

    'xgb_weight': 0.2,

    'threshold': 0.5
}

In [74]:
model_metrics = {
    "roc_auc": ensemble_auc,
    "cat_weight": 0.5,
    "lgb_weight": 0.3,
    "xgb_weight": 0.2,
    "threshold": 0.5
}

## Exporting the models ,encoders and ensemble info

In [75]:
model_export_path = Path("../streamlit/models")
if not model_export_path.exists():
    root = Tk()
    root.withdraw()
    model_export_path = Path(askdirectory(title="Select the directory containing the cleaned data"))

In [76]:
joblib.dump(cat_final,model_export_path/'catboost_model.pkl')

joblib.dump(lgb_final,model_export_path/'lightgbm_model.pkl')

joblib.dump(xgb_final,model_export_path/'xgboost_model.pkl')

joblib.dump(encoders,model_export_path/'encoders.pkl')

joblib.dump(X.columns.tolist(),model_export_path/'feature_columns.pkl')

joblib.dump(ensemble_info,model_export_path/'ensemble_info.pkl')

joblib.dump(model_metrics,model_export_path / "model_metrics.pkl")

['..\\streamlit\\models\\model_metrics.pkl']